# Agnes 2.0 — AI Supply Chain Decision-Support System
**Spherecast Hackathon 2026 | Team: el-musleh**

Agnes analyzes **historical procurement decisions** stored in the supply chain database — the BOMs, supplier relationships, and ingredient purchases that CPG companies have made in the past — and uses AI to find where those decisions are fragmented, risky, or sub-optimal.

**Agnes 2.0 pipeline:**
1. **Ingest** fragmented BOM data from 60 CPG companies (143 shared ingredients, 1,214 BOM appearances)
2. **Risk Heat Map** — score every ingredient by supply chain vulnerability
3. **Go-Fish Trust Score** — track supplier reliability history to adjust recommendations
4. **LLM Substitutability** — Gemini evaluates compliance with evidence trails
5. **Disruption Simulator** — "What if a supplier goes offline?" auto-reroutes
6. **Buying Consortium (GPO)** — identify group purchasing opportunities
7. **Executive Dashboard** — ranked action list across all 143 ingredients

**Agnes 2.0 — OR Enhancements (new cells):**
- **Cell 6-OR** — ILP Supplier Selection (Integer Linear Programming via PuLP/CBC)
- **Cell 8-OR** — Bayesian Beta-Binomial Trust Score (replaces additive ±10/20 heuristic)
- **Cell 9-OR** — TOPSIS Multi-Attribute Risk Heat Map + HHI + Shannon Entropy
- **Cell 11-OR** — Shapley Value GPO (cooperative game theory for fair savings allocation)

> Full OR methods reference: `docs/OR_Methods.md`

---

In [1]:
# ─────────────────────────────────────────────────────────────
# CELL 1 — Environment Setup
# ─────────────────────────────────────────────────────────────

import sqlite3
import json
import os
import random
import pandas as pd
from dotenv import load_dotenv

load_dotenv()  # loads GEMINI_API_KEY from .env into os.environ

try:
    from google import genai
    from google.genai import types
    from importlib.metadata import version
except ImportError:
    raise ImportError(
        "The 'google-genai' package is required.\n"
        "Install it with:  pip install google-genai"
    )

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))
DB_PATH = "DB/db.sqlite"

pd.set_option("display.max_colwidth", 80)
pd.set_option("display.max_rows", 60)

print("Agnes v2.0 — AI Supply Chain Decision-Support System")
print(f"Google GenAI SDK  : {version('google-genai')}")
print(f"Database          : {os.path.abspath(DB_PATH)}")
print(f"API key loaded    : {'YES' if os.environ.get('GEMINI_API_KEY') else 'NO — check .env'}")

Agnes v2.0 — AI Supply Chain Decision-Support System
Google GenAI SDK  : 1.73.1
Database          : /mnt/nvme0n1p6/Notebooks/Projects/Hackathon 2026/DB/db.sqlite
API key loaded    : YES

## 🗄️ Database Architecture & Functioning
The underlying supply chain data is modeled in a local SQLite database (`DB/db.sqlite`).
It maps out the relationships between CPG companies, their finished goods, raw material ingredients, bill of materials (BOM), and material suppliers.

### Core Tables
1. **`Company`**: CPG companies producing finished goods (e.g., Nature Made).
2. **`Product`**: Items in the supply chain, either `finished-good` or `raw-material`.
   - Raw material SKUs follow the format: `RM-C{CompanyId}-{ingredient-name}-{hash}`
3. **`BOM` (Bill of Materials)**: Represents a formulation/recipe for a specific finished product.
4. **`BOM_Component`**: The mapping of raw materials consumed by a specific BOM.
5. **`Supplier`**: Raw material suppliers (e.g., Prinova USA, PureBulk).
6. **`Supplier_Product`**: Maps which raw materials can be provided by which suppliers.

### Sample Data Fetch: `Product` Table
| Id | SKU | CompanyId | Type |
| --- | --- | --- | --- |
| 1 | FG-iherb-10421 | 28 | finished-good |
| 2 | FG-iherb-116514 | 6 | finished-good |
| 3 | FG-iherb-71022 | 56 | finished-good |
| 4 | FG-iherb-52816 | 33 | finished-good |

### Sample Data Fetch: `BOM_Component` Table
| BOMId | ConsumedProductId |
| --- | --- |
| 1 | 506 |
| 1 | 509 |
| 1 | 511 |
| 1 | 512 |

### How it Works
This relational model allows Agnes to identify when multiple companies are independently purchasing the **same ingredient**. By parsing the ingredient name out of the raw material SKU, the system can group demand and trace it back to the total number of finished goods (BOM appearances) that rely on it, revealing powerful consolidation opportunities.
---

In [2]:
# ─────────────────────────────────────────────────────────────
# CELL 1.5 — Database Exploration (Optional)
# ─────────────────────────────────────────────────────────────
# This cell demonstrates how Agnes interacts with the database.
import sqlite3
import pandas as pd

conn = sqlite3.connect(DB_PATH)

print("Sample rows from Product table:")
display(pd.read_sql_query("SELECT * FROM Product LIMIT 5", conn))

print("\nSample rows from BOM_Component table:")
display(pd.read_sql_query("SELECT * FROM BOM_Component LIMIT 5", conn))

conn.close()

Sample rows from Product table:

   Id              SKU  CompanyId           Type
0   1   FG-iherb-10421         28  finished-good
1   2  FG-iherb-116514          6  finished-good
2   3   FG-iherb-71022         56  finished-good
3   4   FG-iherb-52816         33  finished-good
4   5   FG-iherb-14689         48  finished-good

Sample rows from BOM_Component table:

   BOMId  ConsumedProductId
0      1                506
1      1                509
2      1                511
3      1                512
4      2                208

In [3]:
# ─────────────────────────────────────────────────────────────
# CELL 2 — Database Connection & Fragmented Demand Ingestion
# ─────────────────────────────────────────────────────────────
# The core insight: raw-material SKUs follow the pattern
#   RM-C{CompanyId}-{ingredient-name}-{8-char-hash}
#
# Parsing the ingredient name out of the SKU reveals that
# multiple CPG companies independently purchase the SAME ingredient
# under separate SKUs — this IS the fragmentation problem Agnes solves.
#
# Parsing formula (works for C1 through C99, multi-dash ingredient names):
#   SUBSTR(SKU, 4 + INSTR(SUBSTR(SKU, 4), '-'))   → strips "RM-C{id}-" prefix
#   SUBSTR(..., 1, LENGTH(...) - 9)                → strips "-{8hexhash}" suffix
# ─────────────────────────────────────────────────────────────

# ── Shared CTE block (reused in both queries) ────────────────────────────────
_CTE_PARSED = """
WITH parsed AS (
    -- Parse the ingredient name out of every raw-material SKU.
    -- The SKU format is RM-C{CompanyId}-{ingredient-name}-{8hexhash}.
    -- Step 1: SUBSTR(SKU, 4)                       → strips leading "RM-"
    -- Step 2: INSTR(…, '-')                         → finds the dash after C{id}
    -- Step 3: SUBSTR(SKU, 4 + offset)               → strips "RM-C{id}-" prefix
    -- Step 4: SUBSTR(…, 1, LENGTH(…) - 9)           → strips trailing "-{8hexhash}"
    SELECT
        p.Id        AS product_id,
        p.SKU,
        p.CompanyId,
        c.Name      AS company_name,
        SUBSTR(
            SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-')),
            1,
            LENGTH(SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-'))) - 9
        ) AS ingredient_name
    FROM Product p
    JOIN Company c ON c.Id = p.CompanyId
    WHERE p.Type = 'raw-material'
),
bom_usage AS (
    -- Count how many finished-good BOMs each raw-material variant feeds into.
    -- This is our proxy for demand volume: one BOM appearance = one finished
    -- product that depends on this ingredient.
    SELECT
        pr.ingredient_name,
        pr.company_name,
        pr.CompanyId,
        pr.product_id,
        pr.SKU,
        COUNT(bc.BOMId) AS bom_appearances
    FROM parsed pr
    JOIN BOM_Component bc ON bc.ConsumedProductId = pr.product_id
    GROUP BY pr.product_id
),
fragmented_ingredients AS (
    -- An ingredient is "fragmented" when MORE THAN ONE company buys it
    -- separately. These are the consolidation opportunities.
    SELECT
        ingredient_name,
        COUNT(DISTINCT CompanyId) AS company_count,
        SUM(bom_appearances)      AS total_bom_appearances
    FROM bom_usage
    GROUP BY ingredient_name
    HAVING company_count > 1
)
"""

# ── Query A: Fragmented Demand ────────────────────────────────────────────────
# One row per (ingredient, company) pair where that ingredient is fragmented.
SQL_FRAGMENTED = _CTE_PARSED + """
SELECT
    fi.ingredient_name,
    fi.company_count,
    fi.total_bom_appearances,
    bu.company_name,
    bu.SKU            AS company_sku,
    bu.product_id,
    bu.bom_appearances
FROM fragmented_ingredients fi
JOIN bom_usage bu ON bu.ingredient_name = fi.ingredient_name
ORDER BY fi.total_bom_appearances DESC, fi.ingredient_name, bu.company_name
"""

# ── Query B: Supplier Coverage for Fragmented Ingredients ────────────────────
# For each fragmented ingredient × company variant, which supplier(s) can deliver?
# This JOIN path: raw-material product → Supplier_Product → Supplier.
SQL_SUPPLIER_COVERAGE = _CTE_PARSED + """
SELECT
    fi.ingredient_name,
    bu.company_name,
    bu.SKU              AS company_sku,
    bu.bom_appearances,
    s.Id                AS supplier_id,
    s.Name              AS supplier_name
FROM fragmented_ingredients fi
JOIN bom_usage bu         ON bu.ingredient_name = fi.ingredient_name
JOIN Supplier_Product sp  ON sp.ProductId        = bu.product_id
JOIN Supplier s           ON s.Id                = sp.SupplierId
ORDER BY fi.total_bom_appearances DESC, bu.ingredient_name, bu.company_name, s.Name
"""

# ── Execute queries ───────────────────────────────────────────────────────────
conn = sqlite3.connect(DB_PATH)
df_fragmented        = pd.read_sql_query(SQL_FRAGMENTED,       conn)
df_supplier_coverage = pd.read_sql_query(SQL_SUPPLIER_COVERAGE, conn)
conn.close()

# ── Summary ───────────────────────────────────────────────────────────────────
n_fragmented   = df_fragmented["ingredient_name"].nunique()
n_companies    = df_fragmented["company_name"].nunique()
n_bom_waste    = df_fragmented.groupby("ingredient_name")["bom_appearances"].sum()

print(f"Fragmented ingredients found : {n_fragmented}")
print(f"CPG companies involved        : {n_companies}")
print(f"Total BOM appearances at risk : {n_bom_waste.sum()}")
print("\nTop 15 consolidation opportunities (by BOM volume):")

display(
    df_fragmented
    .groupby("ingredient_name")
    .agg(
        companies  = ("company_name",       "nunique"),
        bom_total  = ("bom_appearances",    "sum"),
        suppliers  = ("ingredient_name",    lambda x: (
            df_supplier_coverage[df_supplier_coverage["ingredient_name"].isin(x)]
            ["supplier_name"].nunique()
        ))
    )
    .sort_values("bom_total", ascending=False)
    .head(15)
    .rename(columns={"companies": "CPG companies", "bom_total": "BOM appearances", "suppliers": "distinct suppliers"})
)

Fragmented ingredients found : 143
CPG companies involved        : 60
Total BOM appearances at risk : 1214

Top 15 consolidation opportunities (by BOM volume):

                            CPG companies  BOM appearances  distinct suppliers
ingredient_name
vitamin-d3-cholecalciferol             17               33                   2
gelatin                                11               30                   2
magnesium-stearate                     11               30                   2
microcrystalline-cellulose             13               29                   2
citric-acid                            12               26                   2
magnesium-oxide                        10               25                   2
silicon-dioxide                        10               25                   2
stearic-acid                            7               24                   2
vitamin-c                              13               24                   2
maltodextrin                            8               21                   1
calcium-carbonate                       8               20                   2
whey-protein-isolate                   11               20                   2
vitamin-a                              10               19                   2
vitamin-e                              10               19                   2
croscarmellose-sodium                   8               19                   2

In [4]:
# ─────────────────────────────────────────────────────────────
# CELL 3 — Target Selection & Finished-Product Impact Trace
# ─────────────────────────────────────────────────────────────
# We choose vitamin-d3-cholecalciferol as our demo target because:
#   • Highest fragmentation: 17 companies buying independently
#   • 33 total BOM appearances → significant combined demand
#   • Only 2 available suppliers (Prinova USA, PureBulk)
#     → zero price leverage today despite the combined volume
#   • Chemistry is unambiguous (cholecalciferol IS vitamin D3)
#     → LLM reasoning will be clean and defensible
#
# We also trace which FINISHED PRODUCTS depend on this ingredient.
# This turns abstract "BOM appearances" into concrete business impact.
# ─────────────────────────────────────────────────────────────

TARGET_INGREDIENT  = "vitamin-d3-cholecalciferol"
RELATED_INGREDIENT = "vitamin-d3"

df_target           = df_fragmented[df_fragmented["ingredient_name"] == TARGET_INGREDIENT].copy()
df_target_suppliers = df_supplier_coverage[df_supplier_coverage["ingredient_name"] == TARGET_INGREDIENT].copy()
df_related          = df_fragmented[df_fragmented["ingredient_name"] == RELATED_INGREDIENT].copy()

print("=" * 65)
print(f"  FRAGMENTATION PROFILE: {TARGET_INGREDIENT}")
print("=" * 65)
print(f"  Companies buying separately : {df_target['company_name'].nunique()}")
print(f"  Total BOM appearances       : {int(df_target['bom_appearances'].sum())}")
print(f"  Distinct supplier options   : {df_target_suppliers['supplier_name'].nunique()}")
print(f"  Unique company SKUs         : {df_target['company_sku'].nunique()}")
print("\nPer-company breakdown:")

display(
    df_target[["company_name", "company_sku", "bom_appearances"]]
    .sort_values("bom_appearances", ascending=False)
    .reset_index(drop=True)
)

print(f"\nSuppliers currently covering this ingredient:")
display(
    df_target_suppliers.groupby("supplier_name")
    .agg(
        companies_served = ("company_name",    "nunique"),
        bom_coverage     = ("bom_appearances",  "sum"),
    )
    .reset_index()
)

# ── Finished-product impact trace ────────────────────────────────────────────
# Follow the chain: raw-material product → BOM_Component → BOM → finished-good
# This shows judges exactly WHICH products would benefit from consolidation.
SQL_FINISHED_PRODUCTS = """
WITH parsed AS (
    SELECT
        p.Id AS rm_product_id,
        c.Name AS company_name,
        SUBSTR(
            SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-')),
            1,
            LENGTH(SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-'))) - 9
        ) AS ingredient_name
    FROM Product p
    JOIN Company c ON c.Id = p.CompanyId
    WHERE p.Type = 'raw-material'
)
SELECT
    pr.company_name,
    pr.ingredient_name,
    fg.SKU AS finished_product_sku
FROM parsed pr
JOIN BOM_Component bc ON bc.ConsumedProductId = pr.rm_product_id
JOIN BOM b             ON b.Id                = bc.BOMId
JOIN Product fg        ON fg.Id               = b.ProducedProductId
WHERE pr.ingredient_name = :ingredient
ORDER BY pr.company_name, fg.SKU
"""

conn = sqlite3.connect(DB_PATH)
df_finished = pd.read_sql_query(SQL_FINISHED_PRODUCTS, conn, params={"ingredient": TARGET_INGREDIENT})
conn.close()

print(f"\nFinished products directly impacted by '{TARGET_INGREDIENT}' fragmentation:")
print(f"({len(df_finished)} finished-good SKUs across {df_finished['company_name'].nunique()} companies)\n")
display(df_finished.head(20))

print(f"\nRelated cluster '{RELATED_INGREDIENT}' (potential cross-cluster sub):")
print(f"  Companies : {df_related['company_name'].nunique()}")
print(f"  BOM total : {int(df_related['bom_appearances'].sum())}")
print(f"\n→ Combined opportunity: {df_target['company_name'].nunique() + df_related['company_name'].nunique()} companies, "
      f"{int(df_target['bom_appearances'].sum() + df_related['bom_appearances'].sum())} BOM appearances")

=================================================================
  FRAGMENTATION PROFILE: vitamin-d3-cholecalciferol
=================================================================
  Companies buying separately : 17
  Total BOM appearances       : 33
  Distinct supplier options   : 2
  Unique company SKUs         : 17

Per-company breakdown:

,company_name,company_sku,bom_appearances
0,Nature Made,RM-C30-vitamin-d3-cholecalciferol-559c9699,11
1,The Vitamin Shoppe,RM-C52-vitamin-d3-cholecalciferol-1d08f804,3
2,Vitacost,RM-C57-vitamin-d3-cholecalciferol-528f4316,3
3,21st Century,RM-C1-vitamin-d3-cholecalciferol-67efce0f,2
4,up&up,RM-C62-vitamin-d3-cholecalciferol-c763da21,2
5,NOW Foods,RM-C28-vitamin-d3-cholecalciferol-8956b79c,1
6,GNC,RM-C19-vitamin-d3-cholecalciferol-3f392102,1
7,Kirkland Signature,RM-C25-vitamin-d3-cholecalciferol-564712ba,1
8,Jarrow Formulas,RM-C24-vitamin-d3-cholecalciferol-0949dd9f,1
9,Nordic Naturals,RM-C34-vitamin-d3-cholecalciferol-7e2cad2a,1
10,Nature's Bounty,RM-C31-vitamin-d3-cholecalciferol-6e6ef79b,1
11,Natural Factors,RM-C29-vitamin-d3-cholecalciferol-aedcde8b,1
12,Ritual,RM-C44-vitamin-d3-cholecalciferol-7429dd7b,1
13,Spring Valley,RM-C50-vitamin-d3-cholecalciferol-22ab18a7,1
14,Sports Research,RM-C49-vitamin-d3-cholecalciferol-0d990e67,1
15,Solgar,RM-C48-vitamin-d3-cholecalciferol-a14e1c25,1
16,Thorne,RM-C53-vitamin-d3-cholecalciferol-d3043492,1

Suppliers currently covering this ingredient:

  supplier_name  companies_served  bom_coverage
0   Prinova USA                17            33
1      PureBulk                17            33

Finished products directly impacted by 'vitamin-d3-cholecalciferol' fragmentation:
(33 finished-good SKUs across 17 companies)

,company_name,ingredient_name,finished_product_sku
0,21st Century,vitamin-d3-cholecalciferol,FG-iherb-cen-27493
1,21st Century,vitamin-d3-cholecalciferol,FG-target-a-1006517338
2,GNC,vitamin-d3-cholecalciferol,FG-gnc-145223
3,Jarrow Formulas,vitamin-d3-cholecalciferol,FG-thrive-market-jarrow-formulas-vitamin-d3-supplement
4,Kirkland Signature,vitamin-d3-cholecalciferol,FG-costco-11467951
5,NOW Foods,vitamin-d3-cholecalciferol,FG-iherb-10421
6,Natural Factors,vitamin-d3-cholecalciferol,FG-iherb-2582
7,Nature Made,vitamin-d3-cholecalciferol,FG-costco-100214136
8,Nature Made,vitamin-d3-cholecalciferol,FG-cvs-486916
9,Nature Made,vitamin-d3-cholecalciferol,FG-cvs-504105
10,Nature Made,vitamin-d3-cholecalciferol,FG-cvs-704167
11,Nature Made,vitamin-d3-cholecalciferol,FG-cvs-843231
12,Nature Made,vitamin-d3-cholecalciferol,FG-target-a-14161820
13,Nature Made,vitamin-d3-cholecalciferol,FG-walgreens-300425544
14,Nature Made,vitamin-d3-cholecalciferol,FG-walgreens-prod2303851
15,Nature Made,vitamin-d3-cholecalciferol,FG-walgreens-prod6031044
16,Nature Made,vitamin-d3-cholecalciferol,FG-walgreens-prod6063885
17,Nature Made,vitamin-d3-cholecalciferol,FG-walgreens-prod6063886
18,Nature's Bounty,vitamin-d3-cholecalciferol,FG-costco-100351325
19,Nordic Naturals,vitamin-d3-cholecalciferol,FG-walmart-109808244

Related cluster 'vitamin-d3' (potential cross-cluster sub):
  Companies : 8
  BOM total : 14

→ Combined opportunity: 25 companies, 47 BOM appearances

In [5]:
# ─────────────────────────────────────────────────────────────
# CELL 4 — External Data Enrichment (Mock Compliance Scraper)
# ─────────────────────────────────────────────────────────────
# In production Agnes would:
#   • Crawl supplier websites (Selenium/Playwright) for CoA PDFs
#   • Query NSF/USP certification databases
#   • Call the FDA Substance Registration System API
#   • Use a multimodal LLM to extract specs from product data sheets
#
# Here we mock that enrichment with realistic, supplier-specific data.
# The mock values for Prinova USA and PureBulk reflect their real-world
# product portfolios. The seeded random fallback ensures reproducibility
# for any other (supplier, ingredient) pair.
# ─────────────────────────────────────────────────────────────

_COMPLIANCE_MOCK_DB = {
    ("Prinova USA", "vitamin-d3-cholecalciferol"): {
        "organic_certified": False,
        "fda_registered":    True,
        "non_gmo":           True,
        "grade":             "pharmaceutical",
        "lead_time_days":    14,
        "certifications":    ["USP", "GMP", "Halal", "Kosher"],
        "notes": "Lanolin-derived cholecalciferol. USP-grade specification sheet available. "
                 "EU REACH compliant. Suitable for dietary supplement labelling.",
    },
    ("PureBulk", "vitamin-d3-cholecalciferol"): {
        "organic_certified": False,
        "fda_registered":    True,
        "non_gmo":           True,
        "grade":             "pharmaceutical",
        "lead_time_days":    7,
        "certifications":    ["GMP", "Kosher"],
        "notes": "Bulk powder, pharmaceutical grade. Shorter lead time. "
                 "Does not carry USP or Halal certificates — fewer third-party audits than Prinova.",
    },
    ("Prinova USA", "vitamin-d3"): {
        "organic_certified": False,
        "fda_registered":    True,
        "non_gmo":           True,
        "grade":             "food",
        "lead_time_days":    14,
        "certifications":    ["GMP", "Kosher"],
        "notes": "Food-grade D3 blend (lower potency spec, not USP monograph). "
                 "Suitable for food fortification; may not satisfy pharma-grade supplement requirements.",
    },
    ("PureBulk", "vitamin-d3"): {
        "organic_certified": False,
        "fda_registered":    True,
        "non_gmo":           False,
        "grade":             "food",
        "lead_time_days":    7,
        "certifications":    ["GMP"],
        "notes": "Standard food-grade D3. No Non-GMO statement on file. "
                 "Single GMP certificate only; limited third-party validation.",
    },
}


def scrape_supplier_compliance(supplier_name: str, ingredient_name: str) -> dict:
    """
    Return a compliance profile for a (supplier, ingredient) pair.

    Keys
    ----
    organic_certified : bool   — USDA/EU organic certification
    fda_registered    : bool   — FDA facility registration
    non_gmo           : bool   — Non-GMO statement on file
    grade             : str    — "pharmaceutical" | "food" | "technical"
    lead_time_days    : int    — typical order-to-delivery lead time
    certifications    : list   — third-party certs (USP, NSF, GMP, Halal, Kosher, ISO …)
    notes             : str    — free-text summary (would come from scraped CoA in prod)
    """
    key = (supplier_name, ingredient_name)
    if key in _COMPLIANCE_MOCK_DB:
        return dict(_COMPLIANCE_MOCK_DB[key])  # return a copy

    # Seeded fallback — deterministic for reproducibility
    rng = random.Random(hash(key) % (2 ** 31))
    return {
        "organic_certified": rng.choice([True, False]),
        "fda_registered":    True,
        "non_gmo":           rng.choice([True, False]),
        "grade":             rng.choice(["pharmaceutical", "food"]),
        "lead_time_days":    rng.randint(7, 45),
        "certifications":    rng.sample(["GMP", "NSF", "USP", "Halal", "Kosher", "ISO"], k=rng.randint(1, 3)),
        "notes":             f"Auto-generated compliance profile for {supplier_name} / {ingredient_name}.",
    }


# ── Preview enrichment for the two suppliers in scope ────────────────────────
suppliers_in_scope = sorted(df_target_suppliers["supplier_name"].unique().tolist())
print(f"Compliance data for '{TARGET_INGREDIENT}' suppliers:\n")
for s in suppliers_in_scope:
    profile = scrape_supplier_compliance(s, TARGET_INGREDIENT)
    print(f"[{s}]")
    for k, v in profile.items():
        print(f"  {k:22s}: {v}")
    print()

Compliance data for 'vitamin-d3-cholecalciferol' suppliers:

[Prinova USA]
  organic_certified     : False
  fda_registered        : True
  non_gmo               : True
  grade                 : pharmaceutical
  lead_time_days        : 14
  certifications        : ['USP', 'GMP', 'Halal', 'Kosher']
  notes                 : Lanolin-derived cholecalciferol. USP-grade specification sheet available. EU REACH compliant. Suitable for dietary supplement labelling.

[PureBulk]
  organic_certified     : False
  fda_registered        : True
  non_gmo               : True
  grade                 : pharmaceutical
  lead_time_days        : 7
  certifications        : ['GMP', 'Kosher']
  notes                 : Bulk powder, pharmaceutical grade. Shorter lead time. Does not carry USP or Halal certificates — fewer third-party audits than Prinova.

In [6]:
# ─────────────────────────────────────────────────────────────
# CELL 5 — LLM Reasoning Agent (Gemini)
# ─────────────────────────────────────────────────────────────
# Agnes uses Gemini to evaluate ingredient substitutability.
# Two evaluations are run:
#
# Eval 1 — Within-cluster (same ingredient, two suppliers)
#   "Can PureBulk substitute for Prinova USA across all 17 companies?"
#   → demonstrates supplier consolidation with compliance check
#
# Eval 2 — Cross-cluster (two ingredient name variants)
#   "Can pharma-grade cholecalciferol replace food-grade vitamin-d3?"
#   → demonstrates nuanced grade-level reasoning
#
# Prompt engineering notes:
#   • System prompt hard-encodes compliance guardrails so the LLM cannot
#     approve a downgrade (pharma→food) without flagging it.
#   • response_mime_type="application/json" forces structured JSON output
#     natively — no markdown fences to strip.
#   • Evidence trail is explicitly required — this is the judge-facing artifact.
#   • Confidence < 0.7 triggers HUMAN_REVIEW_REQUIRED, giving judges the
#     trustworthiness signal they are looking for.
# ─────────────────────────────────────────────────────────────

AGNES_SYSTEM_PROMPT = """You are Agnes, an AI supply chain reasoning agent for the CPG (Consumer Packaged Goods) industry.
Your role is to evaluate whether two raw-material ingredient variants are functionally substitutable for sourcing consolidation purposes.

You reason carefully from:
1. Chemical and functional identity of the ingredients
2. Regulatory grade requirements (pharmaceutical vs. food vs. technical)
3. Certifications required by the end products (USP, NSF, GMP, Halal, Kosher, Non-GMO, Organic)
4. Lead time feasibility
5. Known industry standards (USP monographs, FDA 21 CFR, EU regulations)

CRITICAL RULES:
- A substitution is only valid if the replacement MEETS OR EXCEEDS the quality and compliance level of the original.
- Downgrading from pharmaceutical grade to food grade is NEVER acceptable without explicit evidence that the finished product only requires food grade.
- A missing certification on the replacement supplier is a compliance gap that must be flagged.
- You must produce an evidence trail: a list of specific, discrete facts that support your conclusion.
- You must never hallucinate certifications or regulatory status. If you are uncertain, state the uncertainty explicitly and lower your confidence score.
- Confidence scores: 0.9+ = high certainty from known chemistry/regulation; 0.7–0.9 = reasonable inference; below 0.7 = uncertain, escalate to human review.

OUTPUT FORMAT: Respond with valid JSON only matching this exact schema:
{
  "substitutable": <bool>,
  "confidence": <float 0.0-1.0>,
  "evidence_trail": ["<fact 1>", "<fact 2>", ...],
  "compliance_met": <bool>,
  "compliance_gaps": ["<gap description if any>"],
  "reasoning": "<2-4 sentence narrative>",
  "recommendation": "<one of: APPROVE | APPROVE_WITH_CONDITIONS | REJECT | HUMAN_REVIEW_REQUIRED>"
}"""


def _build_prompt(
    ingredient_a: str, supplier_a: str, compliance_a: dict,
    ingredient_b: str, supplier_b: str, compliance_b: dict,
    context_companies: list, context_bom_appearances: int,
) -> str:
    """Build the user-turn message for the substitutability evaluation."""
    company_list = ', '.join(context_companies[:5])
    if len(context_companies) > 5:
        company_list += f" … (+{len(context_companies) - 5} more)"

    return f"""## Substitutability Evaluation Request

### Ingredient A — Current (consolidate FROM)
- Ingredient name   : {ingredient_a}
- Supplier          : {supplier_a}
- FDA registered    : {compliance_a['fda_registered']}
- Grade             : {compliance_a['grade']}
- Non-GMO           : {compliance_a['non_gmo']}
- Organic           : {compliance_a['organic_certified']}
- Certifications    : {', '.join(compliance_a['certifications'])}
- Lead time         : {compliance_a['lead_time_days']} days
- Supplier notes    : {compliance_a['notes']}

### Ingredient B — Proposed (consolidate TO)
- Ingredient name   : {ingredient_b}
- Supplier          : {supplier_b}
- FDA registered    : {compliance_b['fda_registered']}
- Grade             : {compliance_b['grade']}
- Non-GMO           : {compliance_b['non_gmo']}
- Organic           : {compliance_b['organic_certified']}
- Certifications    : {', '.join(compliance_b['certifications'])}
- Lead time         : {compliance_b['lead_time_days']} days
- Supplier notes    : {compliance_b['notes']}

### Business Context
- CPG companies affected : {company_list}
- Total BOM appearances  : {context_bom_appearances}
- Consolidation goal     : Replace all company-specific SKUs with one consolidated purchase order

### Question
Can Ingredient B (from {supplier_b}) substitute for Ingredient A (from {supplier_a}) across all affected CPG companies' BOMs while maintaining full quality and compliance?
Provide your structured JSON evaluation."""


def evaluate_substitutability(
    ingredient_a: str, supplier_a: str, compliance_a: dict,
    ingredient_b: str, supplier_b: str, compliance_b: dict,
    context_companies: list, context_bom_appearances: int,
    model_name: str = "gemini-flash-latest",
) -> dict:
    """
    Call Gemini to evaluate ingredient substitutability.
    Returns a parsed dict matching the JSON schema in AGNES_SYSTEM_PROMPT.
    Falls back to a safe error dict if the response cannot be parsed.
    """
    user_message = _build_prompt(
        ingredient_a, supplier_a, compliance_a,
        ingredient_b, supplier_b, compliance_b,
        context_companies, context_bom_appearances,
    )

    # response_mime_type="application/json" tells Gemini to return
    # structured JSON directly — no markdown fences to strip.
    response = client.models.generate_content(
        model=model_name,
        contents=user_message,
        config=types.GenerateContentConfig(
            system_instruction=AGNES_SYSTEM_PROMPT,
            response_mime_type="application/json",
            temperature=0.2,   # low temp for consistent, factual reasoning
        ),
    )

    raw_text = response.text.strip()

    try:
        result = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        result = {
            "substitutable":  False,
            "confidence":     0.0,
            "evidence_trail": [f"JSON parse error: {exc}", f"Raw: {raw_text[:300]}"],
            "compliance_met": False,
            "compliance_gaps": ["LLM response could not be parsed — requires manual review"],
            "reasoning":      "Parse failure.",
            "recommendation": "HUMAN_REVIEW_REQUIRED",
        }

    # Attach call metadata for traceability
    usage = response.usage_metadata
    result["_meta"] = {
        "model":          model_name,
        "input_tokens":   usage.prompt_token_count,
        "output_tokens":  usage.candidates_token_count,
        "ingredient_a":   ingredient_a,
        "supplier_a":     supplier_a,
        "ingredient_b":   ingredient_b,
        "supplier_b":     supplier_b,
    }
    return result


# ── Run Evaluation 1: Supplier consolidation (same ingredient) ───────────────
companies_vd3      = df_target["company_name"].unique().tolist()
bom_total_vd3      = int(df_target["bom_appearances"].sum())
comp_prinova_chol  = scrape_supplier_compliance("Prinova USA", TARGET_INGREDIENT)
comp_purebulk_chol = scrape_supplier_compliance("PureBulk",   TARGET_INGREDIENT)

print("Running Evaluation 1 — Supplier consolidation (same ingredient) …")
eval_within_cluster = evaluate_substitutability(
    ingredient_a=TARGET_INGREDIENT,  supplier_a="Prinova USA",  compliance_a=comp_prinova_chol,
    ingredient_b=TARGET_INGREDIENT,  supplier_b="PureBulk",     compliance_b=comp_purebulk_chol,
    context_companies=companies_vd3, context_bom_appearances=bom_total_vd3,
)

print(f"\n=== Eval 1: Can PureBulk replace Prinova USA for {TARGET_INGREDIENT}? ===")
print(f"  Recommendation : {eval_within_cluster['recommendation']}")
print(f"  Substitutable  : {eval_within_cluster['substitutable']}")
print(f"  Confidence     : {eval_within_cluster['confidence']:.0%}")
print(f"  Compliance met : {eval_within_cluster['compliance_met']}")
if eval_within_cluster.get("compliance_gaps"):
    for gap in eval_within_cluster["compliance_gaps"]:
        print(f"  ⚠ Gap         : {gap}")
print("  Evidence trail:")
for fact in eval_within_cluster["evidence_trail"]:
    print(f"    • {fact}")
print(f"  Reasoning      : {eval_within_cluster['reasoning']}")
print(f"  Tokens used    : {eval_within_cluster['_meta']['input_tokens']} in / "
      f"{eval_within_cluster['_meta']['output_tokens']} out")


# ── Run Evaluation 2: Cross-cluster (food-grade vs pharma-grade) ─────────────
companies_related  = df_related["company_name"].unique().tolist()
bom_total_related  = int(df_related["bom_appearances"].sum())
comp_prinova_vd3   = scrape_supplier_compliance("Prinova USA", RELATED_INGREDIENT)
comp_prinova_chol2 = scrape_supplier_compliance("Prinova USA", TARGET_INGREDIENT)

print("\nRunning Evaluation 2 — Cross-cluster grade comparison …")
eval_cross_cluster = evaluate_substitutability(
    ingredient_a=RELATED_INGREDIENT, supplier_a="Prinova USA", compliance_a=comp_prinova_vd3,
    ingredient_b=TARGET_INGREDIENT,  supplier_b="Prinova USA", compliance_b=comp_prinova_chol2,
    context_companies=companies_related, context_bom_appearances=bom_total_related,
)

print(f"\n=== Eval 2: Can pharma-grade cholecalciferol replace food-grade vitamin-d3? ===")
print(f"  Recommendation : {eval_cross_cluster['recommendation']}")
print(f"  Substitutable  : {eval_cross_cluster['substitutable']}")
print(f"  Confidence     : {eval_cross_cluster['confidence']:.0%}")
print(f"  Compliance met : {eval_cross_cluster['compliance_met']}")
print(f"  Reasoning      : {eval_cross_cluster['reasoning']}")

Running Evaluation 1 — Supplier consolidation (same ingredient) …

=== Eval 1: Can PureBulk replace Prinova USA for vitamin-d3-cholecalciferol? ===
  Recommendation : REJECT
  Substitutable  : False
  Confidence     : 95%
  Compliance met : False
  ⚠ Gap         : Missing USP (United States Pharmacopeia) certification
  ⚠ Gap         : Missing Halal certification
  Evidence trail:
    • Ingredient A carries USP certification, which is a critical quality standard for pharmaceutical-grade dietary supplements in the US market.
    • Ingredient A is Halal certified, whereas Ingredient B is not.
    • Ingredient B lacks third-party USP verification, which is often a non-negotiable requirement for major retailers like Kirkland Signature and GNC.
    • Consolidation across 33 BOMs requires the replacement to meet the 'highest common denominator' of certifications to avoid product-specific compliance failures.
  Reasoning      : While Ingredient B is listed as pharmaceutical grade, it fails to meet the compliance profile of Ingredient A due to the absence of USP and Halal certifications. For major CPG brands like GNC and Kirkland, USP verification is a primary quality benchmark, and removing Halal status would invalidate the certification of any finished products currently making that claim.
  Tokens used    : 783 in / 267 out

Running Evaluation 2 — Cross-cluster grade comparison …

=== Eval 2: Can pharma-grade cholecalciferol replace food-grade vitamin-d3? ===
  Recommendation : APPROVE
  Substitutable  : True
  Confidence     : 98%
  Compliance met : True
  Reasoning      : Ingredient B is a direct quality upgrade from Ingredient A, moving from a food-grade blend to a pharmaceutical-grade USP cholecalciferol. Since Ingredient B meets or exceeds all regulatory, certification, and potency requirements of Ingredient A while originating from the same supplier, it is a low-risk candidate for consolidation.

In [7]:
# ─────────────────────────────────────────────────────────────
# CELL 6 — Optimization & Supplier Consolidation Algorithm
# ─────────────────────────────────────────────────────────────
# Ranking formula: consolidated_score = bom_appearances_covered × compliance_weight
#
# Approved recommendations (in order of confidence):
#   APPROVE                  → included, no conditions
#   APPROVE_WITH_CONDITIONS  → included, flagged
#   HUMAN_REVIEW_REQUIRED    → included as conditional, flagged
#   REJECT                   → excluded entirely
# ─────────────────────────────────────────────────────────────

_APPROVED_STATUSES = {"APPROVE", "APPROVE_WITH_CONDITIONS", "HUMAN_REVIEW_REQUIRED"}


def compute_compliance_weight(compliance: dict) -> float:
    """Score a supplier's compliance profile. Higher = better. Range ~0.1–1.8."""
    weight = 1.0
    if compliance.get("grade") == "pharmaceutical":
        weight += 0.2
    elif compliance.get("grade") == "technical":
        weight -= 0.3
    if compliance.get("fda_registered"):
        weight += 0.1
    if compliance.get("non_gmo"):
        weight += 0.1
    cert_bonus = min(0.30, len(compliance.get("certifications", [])) * 0.05)
    weight += cert_bonus
    return round(max(0.1, weight), 3)


def consolidate_sourcing(
    ingredient_name: str,
    df_supplier_coverage: pd.DataFrame,
    approved_evaluations: list,
    scrape_fn,
) -> pd.DataFrame:
    """
    Produce a ranked sourcing recommendation for a given ingredient.
    Includes APPROVE, APPROVE_WITH_CONDITIONS, and HUMAN_REVIEW_REQUIRED.
    Excludes only REJECT.
    """
    # Debug: show what recommendations came back
    for ev in approved_evaluations:
        rec = ev.get("recommendation", "UNKNOWN")
        sup = ev["_meta"]["supplier_b"]
        print(f"  Evaluation result — {sup}: {rec}")

    approved_suppliers = {
        ev["_meta"]["supplier_b"]
        for ev in approved_evaluations
        if ev.get("recommendation") in _APPROVED_STATUSES
    }

    if not approved_suppliers:
        print(f"\nNo approvable suppliers for '{ingredient_name}' (all were REJECT).")
        return pd.DataFrame()

    df_ing = df_supplier_coverage[
        (df_supplier_coverage["ingredient_name"] == ingredient_name) &
        (df_supplier_coverage["supplier_name"].isin(approved_suppliers))
    ].copy()

    if df_ing.empty:
        print(f"No coverage data found for approved suppliers of '{ingredient_name}'.")
        return pd.DataFrame()

    df_agg = (
        df_ing.groupby("supplier_name")
        .agg(
            bom_appearances_covered = ("bom_appearances", "sum"),
            companies_covered       = ("company_name",   "nunique"),
        )
        .reset_index()
    )

    # Build recommendation label per supplier
    rec_map = {
        ev["_meta"]["supplier_b"]: ev.get("recommendation", "UNKNOWN")
        for ev in approved_evaluations
    }

    rows = []
    for _, row in df_agg.iterrows():
        comp   = scrape_fn(row["supplier_name"], ingredient_name)
        weight = compute_compliance_weight(comp)
        score  = round(row["bom_appearances_covered"] * weight, 2)
        rows.append({
            "supplier_name":           row["supplier_name"],
            "bom_appearances_covered": int(row["bom_appearances_covered"]),
            "companies_covered":       int(row["companies_covered"]),
            "grade":                   comp["grade"],
            "certifications":          ", ".join(comp["certifications"]),
            "lead_time_days":          comp["lead_time_days"],
            "fda_registered":          comp["fda_registered"],
            "non_gmo":                 comp["non_gmo"],
            "compliance_weight":       weight,
            "consolidated_score":      score,
            "llm_verdict":             rec_map.get(row["supplier_name"], "—"),
        })

    df_result = (
        pd.DataFrame(rows)
        .sort_values("consolidated_score", ascending=False)
        .reset_index(drop=True)
    )
    df_result.insert(0, "rank", df_result.index + 1)
    df_result["agnes_recommendation"] = df_result["rank"].map(
        {1: "PRIMARY SUPPLIER", 2: "SECONDARY / BACKUP"}
    ).fillna("MONITOR")

    return df_result


# ── Run consolidation ─────────────────────────────────────────────────────────
print("Consolidation input — LLM verdicts:")
df_recommendation = consolidate_sourcing(
    ingredient_name=TARGET_INGREDIENT,
    df_supplier_coverage=df_supplier_coverage,
    approved_evaluations=[eval_within_cluster],
    scrape_fn=scrape_supplier_compliance,
)

print("\nSupplier ranking:")
display(df_recommendation)

Consolidation input — LLM verdicts:
  Evaluation result — PureBulk: REJECT

No approvable suppliers for 'vitamin-d3-cholecalciferol' (all were REJECT).

Supplier ranking:

Empty DataFrame
Columns: []
Index: []

In [ ]:
# ─────────────────────────────────────────────────────────────
# CELL 6-OR — ILP Optimal Supplier Selection
# ─────────────────────────────────────────────────────────────
# Replaces the heuristic weighted-score ranking with a provably
# optimal Integer Linear Program solved by the CBC MILP solver.
#
# Decision variables:
#   x_s ∈ {0, 1}   for each supplier s   (1 = selected into portfolio)
#
# Objective:
#   maximize  Σ_s [ bom_coverage(s) × compliance_weight(s) × x_s ]
#
# Constraints:
#   1. Σ_s x_s ≥ 1                       (at least one supplier selected)
#   2. x_s = 0  if LLM verdict = REJECT  (hard compliance filter)
#   3. x_s = 0  if lead_time > MAX       (lead-time feasibility)
#   4. x_s = 0  if compliance_weight < MIN (quality floor)
#
# The heuristic in Cell 6 is equivalent to sorting by the objective
# coefficient, but CANNOT express hard constraints — it post-filters
# REJECT suppliers AFTER computing scores. The ILP encodes the LLM
# verdict as a structural constraint before optimisation.
#
# Library: PuLP (open-source LP/ILP solver, CBC backend)
# ─────────────────────────────────────────────────────────────

import pulp

ILP_MAX_LEAD_TIME    = 30     # days — hard cut-off
ILP_MIN_COMPLIANCE   = 1.0   # minimum compliance weight to be eligible


def ilp_supplier_selection(
    ingredient_name: str,
    df_supplier_coverage: pd.DataFrame,
    approved_evaluations: list,
    scrape_fn,
    max_lead_time: int = ILP_MAX_LEAD_TIME,
    min_compliance: float = ILP_MIN_COMPLIANCE,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Optimal supplier portfolio selection via ILP.
    Returns a DataFrame of all candidates with ILP selection status.
    """
    # Hard-reject any supplier with LLM verdict REJECT
    rejected_suppliers = {
        ev["_meta"]["supplier_b"]
        for ev in approved_evaluations
        if ev.get("recommendation") == "REJECT"
    }

    df_ing = df_supplier_coverage[
        df_supplier_coverage["ingredient_name"] == ingredient_name
    ].copy()
    if df_ing.empty:
        print(f"  No coverage data for '{ingredient_name}'.")
        return pd.DataFrame()

    df_agg = (
        df_ing.groupby("supplier_name")
        .agg(
            bom_coverage     = ("bom_appearances", "sum"),
            companies_covered = ("company_name",   "nunique"),
        )
        .reset_index()
    )

    # Enrich with compliance data
    cand = {}
    for _, row in df_agg.iterrows():
        s    = row["supplier_name"]
        comp = scrape_fn(s, ingredient_name)
        cw   = compute_compliance_weight(comp)
        cand[s] = {
            "bom_coverage":      int(row["bom_coverage"]),
            "companies_covered": int(row["companies_covered"]),
            "compliance_weight": cw,
            "lead_time_days":    comp["lead_time_days"],
            "grade":             comp["grade"],
            "certifications":    comp["certifications"],
            "fda_registered":    comp["fda_registered"],
            "non_gmo":           comp["non_gmo"],
            "rejected_llm":      s in rejected_suppliers,
            "obj_coeff":         round(row["bom_coverage"] * cw, 4),
        }

    suppliers = list(cand.keys())
    if not suppliers:
        print("  No candidates found.")
        return pd.DataFrame()

    # ── Build ILP ─────────────────────────────────────────────────────────────
    prob = pulp.LpProblem(f"supplier_selection", pulp.LpMaximize)
    x    = {s: pulp.LpVariable(f"x_{i}", cat="Binary") for i, s in enumerate(suppliers)}

    # Objective
    prob += pulp.lpSum(cand[s]["obj_coeff"] * x[s] for s in suppliers)

    # Constraint 1: at least one supplier
    prob += pulp.lpSum(x[s] for s in suppliers) >= 1, "min_one_supplier"

    # Constraints 2–4: hard exclusions
    for s in suppliers:
        tag = s.replace(" ", "_").replace("&", "")
        if cand[s]["rejected_llm"]:
            prob += x[s] == 0, f"llm_reject_{tag}"
        if cand[s]["lead_time_days"] > max_lead_time:
            prob += x[s] == 0, f"lead_time_{tag}"
        if cand[s]["compliance_weight"] < min_compliance:
            prob += x[s] == 0, f"compliance_floor_{tag}"

    # ── Solve ─────────────────────────────────────────────────────────────────
    status = prob.solve(pulp.PULP_CBC_CMD(msg=0))

    obj_val   = pulp.value(prob.objective) or 0.0
    n_rej_llm = sum(1 for s in suppliers if cand[s]["rejected_llm"])
    n_rej_lt  = sum(1 for s in suppliers if cand[s]["lead_time_days"] > max_lead_time)
    n_rej_cw  = sum(1 for s in suppliers if cand[s]["compliance_weight"] < min_compliance)

    if verbose:
        print(f"\n  ILP solver status     : {pulp.LpStatus[status]}")
        print(f"  Optimal objective     : {obj_val:.3f}")
        print(f"  Suppliers evaluated   : {len(suppliers)}")
        print(f"  Excluded (LLM REJECT) : {n_rej_llm}")
        print(f"  Excluded (lead time)  : {n_rej_lt}")
        print(f"  Excluded (compliance) : {n_rej_cw}")

    # ── Results ───────────────────────────────────────────────────────────────
    rows = []
    for s in suppliers:
        sel = bool(round(pulp.value(x[s]) or 0))
        d   = cand[s]
        rows.append({
            "supplier_name":      s,
            "ilp_selected":       sel,
            "bom_coverage":       d["bom_coverage"],
            "companies_covered":  d["companies_covered"],
            "grade":              d["grade"],
            "certifications":     ", ".join(d["certifications"]),
            "lead_time_days":     d["lead_time_days"],
            "compliance_weight":  d["compliance_weight"],
            "obj_contribution":   d["obj_coeff"],
            "excluded_llm_reject": d["rejected_llm"],
        })

    df_ilp = (
        pd.DataFrame(rows)
        .sort_values(["ilp_selected", "obj_contribution"], ascending=[False, False])
        .reset_index(drop=True)
    )
    df_ilp.insert(0, "rank", df_ilp.index + 1)
    df_ilp["ilp_label"] = df_ilp.apply(
        lambda r: ("✅ PRIMARY" if r["ilp_selected"] and r["rank"] == 1
                   else "✅ BACKUP"  if r["ilp_selected"]
                   else "❌ EXCLUDED"),
        axis=1,
    )
    return df_ilp


# ── Run ILP ───────────────────────────────────────────────────────────────────
SEP = "=" * 65
print(SEP)
print("  CELL 6-OR: ILP OPTIMAL SUPPLIER SELECTION")
print(f"  Ingredient : {TARGET_INGREDIENT}")
print(f"  Solver     : PuLP / CBC (open-source MILP solver)")
print(SEP)
print(f"\n  Hard constraints:")
print(f"    LLM verdict = REJECT  → x_s = 0 (structural, not post-hoc filter)")
print(f"    Lead time   > {ILP_MAX_LEAD_TIME} days  → x_s = 0")
print(f"    Compliance  < {ILP_MIN_COMPLIANCE}       → x_s = 0")

df_ilp_result = ilp_supplier_selection(
    ingredient_name=TARGET_INGREDIENT,
    df_supplier_coverage=df_supplier_coverage,
    approved_evaluations=[eval_within_cluster, eval_cross_cluster],
    scrape_fn=scrape_supplier_compliance,
    verbose=True,
)

print("\nILP Supplier Portfolio:")
display(df_ilp_result[[
    "rank", "supplier_name", "ilp_selected", "bom_coverage",
    "compliance_weight", "obj_contribution", "lead_time_days",
    "excluded_llm_reject", "ilp_label"
]])

# ── Scale-out: run ILP across top-5 fragmented ingredients ───────────────────
print(f"\n{'─'*65}")
print("  ILP across top-5 fragmented ingredients (scale-out demo)")
print(f"{'─'*65}")

top5_ingredients = (
    df_fragmented.groupby("ingredient_name")["bom_appearances"]
    .sum().nlargest(5).index.tolist()
)

for ing in top5_ingredients:
    suppliers_ing = df_supplier_coverage[
        df_supplier_coverage["ingredient_name"] == ing
    ]["supplier_name"].unique().tolist()

    # Build a no-verdict evaluation list (all APPROVE) for scale-out demo
    fake_evals = [
        {"_meta": {"supplier_b": s}, "recommendation": "APPROVE"}
        for s in suppliers_ing
    ]
    df_scaled = ilp_supplier_selection(
        ingredient_name=ing,
        df_supplier_coverage=df_supplier_coverage,
        approved_evaluations=fake_evals,
        scrape_fn=scrape_supplier_compliance,
        verbose=False,
    )
    n_selected = df_scaled["ilp_selected"].sum() if not df_scaled.empty else 0
    obj_val    = df_scaled[df_scaled["ilp_selected"]]["obj_contribution"].sum() if not df_scaled.empty else 0
    print(f"  {ing:<35} → {n_selected} selected  | obj = {obj_val:.1f}")

print(f"\n  ILP guarantees optimality for each ingredient independently.")
print(f"  A multi-ingredient ILP (Set Covering) would add cross-ingredient")
print(f"  supplier consolidation constraints — see docs/OR_Methods.md.")

In [8]:
# ─────────────────────────────────────────────────────────────
# CELL 7 — Final Sourcing Recommendation Output
# ─────────────────────────────────────────────────────────────

SEP  = "=" * 70
SEP2 = "─" * 70

print(SEP)
print("  AGNES — CONSOLIDATED SOURCING RECOMMENDATION")
print(SEP)
print(f"  Ingredient   : {TARGET_INGREDIENT}")
print(f"  Scope        : {df_target['company_name'].nunique()} CPG companies, "
      f"{int(df_target['bom_appearances'].sum())} BOM appearances")
print(f"  LLM model    : {eval_within_cluster['_meta']['model']}")
print(SEP)

# ── Recommendation table ──────────────────────────────────────────────────────
if df_recommendation.empty:
    print("\nNo suppliers passed the consolidation filter.")
else:
    print("\nSupplier Ranking:")
    display(
        df_recommendation[[
            "rank", "supplier_name", "bom_appearances_covered", "companies_covered",
            "grade", "certifications", "lead_time_days",
            "compliance_weight", "consolidated_score", "llm_verdict", "agnes_recommendation",
        ]]
    )

    winner = df_recommendation.iloc[0]
    print(f"\n{SEP2}")
    print("RECOMMENDED ACTION")
    print(SEP2)
    print(f"  Consolidate all {df_target['company_sku'].nunique()} company-specific SKUs")
    print(f"  into a single purchase agreement with: {winner['supplier_name']}")
    print(f"  Volume coverage  : {winner['companies_covered']} companies, "
          f"{winner['bom_appearances_covered']} BOM appearances")
    print(f"  Grade            : {winner['grade']}")
    print(f"  Certifications   : {winner['certifications']}")
    print(f"  Lead time        : {winner['lead_time_days']} days")
    print(f"  Compliance score : {winner['compliance_weight']}")
    print(f"  Agnes score      : {winner['consolidated_score']}")
    print(f"  LLM verdict      : {winner['llm_verdict']}")

# ── Evidence trail ────────────────────────────────────────────────────────────
print(f"\n{SEP2}")
print("EVIDENCE TRAIL (AI Reasoning — Evaluation 1: Supplier Consolidation)")
print(SEP2)
for i, fact in enumerate(eval_within_cluster["evidence_trail"], 1):
    print(f"  [{i}] {fact}")
print(f"\n  LLM confidence   : {eval_within_cluster['confidence']:.0%}")
print(f"  Compliance status: {'PASSED' if eval_within_cluster['compliance_met'] else 'GAPS IDENTIFIED'}")
if eval_within_cluster.get("compliance_gaps"):
    for gap in eval_within_cluster["compliance_gaps"]:
        print(f"  ⚠ Gap: {gap}")
print(f"\n  Reasoning summary:")
print(f"  {eval_within_cluster['reasoning']}")

# ── Cross-cluster evaluation summary ─────────────────────────────────────────
print(f"\n{SEP2}")
print("EVIDENCE TRAIL (AI Reasoning — Evaluation 2: Cross-Cluster Grade Check)")
print(SEP2)
for i, fact in enumerate(eval_cross_cluster["evidence_trail"], 1):
    print(f"  [{i}] {fact}")
print(f"\n  Recommendation   : {eval_cross_cluster['recommendation']}")
print(f"  Reasoning summary:")
print(f"  {eval_cross_cluster['reasoning']}")

# ── Fragmentation waste summary ───────────────────────────────────────────────
print(f"\n{SEP2}")
print("FRAGMENTATION ANALYSIS")
print(SEP2)
print(f"  {df_target['company_name'].nunique()} CPG companies buying the SAME ingredient separately")
print(f"  across {df_target['company_sku'].nunique()} unique SKUs")
print(f"  from only {df_target_suppliers['supplier_name'].nunique()} suppliers")
print(f"  → Zero combined-volume leverage today")
if not df_recommendation.empty:
    winner = df_recommendation.iloc[0]
    print(f"  → Agnes recommendation: single consolidated contract with {winner['supplier_name']}")
    print(f"    Est. combined demand : {winner['bom_appearances_covered']} BOM-level orders")
print(SEP)

======================================================================
  AGNES — CONSOLIDATED SOURCING RECOMMENDATION
======================================================================
  Ingredient   : vitamin-d3-cholecalciferol
  Scope        : 17 CPG companies, 33 BOM appearances
  LLM model    : gemini-flash-latest
======================================================================

No suppliers passed the consolidation filter.

──────────────────────────────────────────────────────────────────────
EVIDENCE TRAIL (AI Reasoning — Evaluation 1: Supplier Consolidation)
──────────────────────────────────────────────────────────────────────
  [1] Ingredient A carries USP certification, which is a critical quality standard for pharmaceutical-grade dietary supplements in the US market.
  [2] Ingredient A is Halal certified, whereas Ingredient B is not.
  [3] Ingredient B lacks third-party USP verification, which is often a non-negotiable requirement for major retailers like Kirkland Signature and GNC.
  [4] Consolidation across 33 BOMs requires the replacement to meet the 'highest common denominator' of certifications to avoid product-specific compliance failures.

  LLM confidence   : 95%
  Compliance status: GAPS IDENTIFIED
  ⚠ Gap: Missing USP (United States Pharmacopeia) certification
  ⚠ Gap: Missing Halal certification

  Reasoning summary:
  While Ingredient B is listed as pharmaceutical grade, it fails to meet the compliance profile of Ingredient A due to the absence of USP and Halal certifications. For major CPG brands like GNC and Kirkland, USP verification is a primary quality benchmark, and removing Halal status would invalidate the certification of any finished products currently making that claim.

──────────────────────────────────────────────────────────────────────
EVIDENCE TRAIL (AI Reasoning — Evaluation 2: Cross-Cluster Grade Check)
──────────────────────────────────────────────────────────────────────
  [1] Both ingredients are Vitamin D3 (Cholecalciferol) sourced from the same supplier (Prinova USA).
  [2] Ingredient B is Pharmaceutical grade (USP), which exceeds the Food grade specification of Ingredient A.
  [3] Ingredient B maintains all certifications held by Ingredient A, including GMP, Kosher, and Non-GMO status.
  [4] Ingredient B adds Halal certification and USP monograph compliance, which were absent in Ingredient A.
  [5] Lead times are identical at 14 days, posing no risk to supply chain continuity.
  [6] The affected brands (e.g., Nature Made, Kirkland Signature) typically require USP-grade ingredients for dietary supplement labeling, which Ingredient B provides.

  Recommendation   : APPROVE
  Reasoning summary:
  Ingredient B is a direct quality upgrade from Ingredient A, moving from a food-grade blend to a pharmaceutical-grade USP cholecalciferol. Since Ingredient B meets or exceeds all regulatory, certification, and potency requirements of Ingredient A while originating from the same supplier, it is a low-risk candidate for consolidation.

──────────────────────────────────────────────────────────────────────
FRAGMENTATION ANALYSIS
──────────────────────────────────────────────────────────────────────
  17 CPG companies buying the SAME ingredient separately
  across 17 unique SKUs
  from only 2 suppliers
  → Zero combined-volume leverage today
======================================================================

In [9]:
# ─────────────────────────────────────────────────────────────
# CELL 8 — Go-Fish Supplier Trust Score
# ─────────────────────────────────────────────────────────────
# Tracks supplier reliability like a go-fish card game:
#   • More on-time deliveries → score increases (+10 per delivery)
#   • Delays / quality incidents → score decreases (−20 per event)
#
# No historical order data exists in the DB, so we generate
# deterministic mock delivery history seeded by supplier name.
# In production Agnes would pull from an ERP / TMS system.
# ─────────────────────────────────────────────────────────────

class SupplierTrustTracker:
    BASE_SCORE   = 100
    ON_TIME_BONUS = 10
    DELAY_PENALTY = 20

    def __init__(self):
        self._scores  = {}
        self._history = {}

    def simulate_history(self, supplier_name: str, n_deliveries: int = 20) -> None:
        rng   = random.Random(hash(supplier_name) % (2 ** 31))
        score = self.BASE_SCORE
        events = []
        for _ in range(n_deliveries):
            on_time = rng.random() < 0.80   # 80 % base on-time rate
            if on_time:
                score += self.ON_TIME_BONUS
                events.append("on_time")
            else:
                score -= self.DELAY_PENALTY
                events.append("delay")
        self._scores[supplier_name]  = max(10, score)
        self._history[supplier_name] = events

    def get_score(self, supplier_name: str) -> int:
        if supplier_name not in self._scores:
            self.simulate_history(supplier_name)
        return self._scores[supplier_name]

    def get_trust_multiplier(self, supplier_name: str) -> float:
        return round(max(0.5, min(1.5, self.get_score(supplier_name) / 100)), 3)

    def get_trust_tier(self, supplier_name: str) -> str:
        s = self.get_score(supplier_name)
        if s >= 160: return "PLATINUM"
        if s >= 130: return "GOLD"
        if s >= 100: return "SILVER"
        if s >= 70:  return "BRONZE"
        return "PROBATION"


# ── Initialise & simulate for all 40 suppliers ───────────────────────────────
trust_tracker = SupplierTrustTracker()

conn = sqlite3.connect(DB_PATH)
all_suppliers = pd.read_sql_query("SELECT Id, Name FROM Supplier ORDER BY Name", conn)
conn.close()

for name in all_suppliers["Name"]:
    trust_tracker.simulate_history(name, n_deliveries=20)

# ── Build leaderboard ─────────────────────────────────────────────────────────
trust_rows = []
for name in all_suppliers["Name"]:
    score   = trust_tracker.get_score(name)
    history = trust_tracker._history[name]
    on_time = history.count("on_time")
    delays  = history.count("delay")
    trust_rows.append({
        "supplier_name":      name,
        "trust_score":        score,
        "trust_tier":         trust_tracker.get_trust_tier(name),
        "trust_multiplier":   trust_tracker.get_trust_multiplier(name),
        "on_time_deliveries": on_time,
        "delays":             delays,
        "on_time_rate":       f"{on_time / 20:.0%}",
    })

df_trust = (
    pd.DataFrame(trust_rows)
    .sort_values("trust_score", ascending=False)
    .reset_index(drop=True)
)
df_trust.insert(0, "rank", df_trust.index + 1)

SEP = "=" * 70
print(SEP)
print("  AGNES — SUPPLIER TRUST LEADERBOARD  (Go-Fish Reliability Score)")
print(SEP)
print(f"  Base score     : {SupplierTrustTracker.BASE_SCORE}")
print(f"  On-time bonus  : +{SupplierTrustTracker.ON_TIME_BONUS} per delivery")
print(f"  Delay penalty  : −{SupplierTrustTracker.DELAY_PENALTY} per incident")
print(f"  Tiers: PROBATION (<70) → BRONZE → SILVER → GOLD → PLATINUM (≥160)")
print(SEP)
display(df_trust)

# ── Show trust impact on vitamin-d3-cholecalciferol suppliers ────────────────
print(f"\nTrust-adjusted compliance weights for '{TARGET_INGREDIENT}' suppliers:")
for s in ["Prinova USA", "PureBulk"]:
    score  = trust_tracker.get_score(s)
    mult   = trust_tracker.get_trust_multiplier(s)
    tier   = trust_tracker.get_trust_tier(s)
    comp   = scrape_supplier_compliance(s, TARGET_INGREDIENT)
    base_w = compute_compliance_weight(comp)
    adj_w  = round(base_w * mult, 3)
    print(f"  {s:15s} | score={score:4d} | tier={tier:9s} | "
          f"compliance={base_w:.3f} × trust={mult:.3f} → adjusted={adj_w:.3f}")

======================================================================
  AGNES — SUPPLIER TRUST LEADERBOARD  (Go-Fish Reliability Score)
======================================================================
  Base score     : 100
  On-time bonus  : +10 per delivery
  Delay penalty  : −20 per incident
  Tiers: PROBATION (<70) → BRONZE → SILVER → GOLD → PLATINUM (≥160)
======================================================================

,rank,supplier_name,trust_score,trust_tier,trust_multiplier,on_time_deliveries,delays,on_time_rate
0,1,Stauber,300,PLATINUM,1.5,20,0,100%
1,2,AIDP,270,PLATINUM,1.5,19,1,95%
2,3,Virginia Dare,270,PLATINUM,1.5,19,1,95%
3,4,Source-Omega LLC,270,PLATINUM,1.5,19,1,95%
4,5,Trace Minerals,270,PLATINUM,1.5,19,1,95%
5,6,Actus Nutrition,240,PLATINUM,1.5,18,2,90%
6,7,American Botanicals,240,PLATINUM,1.5,18,2,90%
7,8,BulkSupplements,240,PLATINUM,1.5,18,2,90%
8,9,Sawgrass Nutra Labs,240,PLATINUM,1.5,18,2,90%
9,10,Custom Probiotics,240,PLATINUM,1.5,18,2,90%
10,11,Nutri Avenue,240,PLATINUM,1.5,18,2,90%
11,12,Vitaquest,240,PLATINUM,1.5,18,2,90%
12,13,Cargill,240,PLATINUM,1.5,18,2,90%
13,14,Sensient,210,PLATINUM,1.5,17,3,85%
14,15,Ashland,210,PLATINUM,1.5,17,3,85%
15,16,Cambrex,210,PLATINUM,1.5,17,3,85%
16,17,Koster Keunen,210,PLATINUM,1.5,17,3,85%
17,18,Mueggenburg USA,210,PLATINUM,1.5,17,3,85%
18,19,Gold Coast Ingredients,210,PLATINUM,1.5,17,3,85%
19,20,Icelandirect,210,PLATINUM,1.5,17,3,85%
20,21,Univar Solutions,210,PLATINUM,1.5,17,3,85%
21,22,Strahl & Pitsch,210,PLATINUM,1.5,17,3,85%
22,23,Balchem,180,PLATINUM,1.5,16,4,80%
23,24,ADM,180,PLATINUM,1.5,16,4,80%
24,25,Capsuline,180,PLATINUM,1.5,16,4,80%
25,26,IFF,180,PLATINUM,1.5,16,4,80%
26,27,PureBulk,180,PLATINUM,1.5,16,4,80%
27,28,Nutra Food Ingredients,180,PLATINUM,1.5,16,4,80%
28,29,TCI America,180,PLATINUM,1.5,16,4,80%
29,30,Specialty Enzymes & Probiotics,180,PLATINUM,1.5,16,4,80%
30,31,Spectrum Chemical,180,PLATINUM,1.5,16,4,80%
31,32,Darling Ingredients / Rousselot,180,PLATINUM,1.5,16,4,80%
32,33,Ingredion,150,GOLD,1.5,15,5,75%
33,34,FutureCeuticals,150,GOLD,1.5,15,5,75%
34,35,Makers Nutrition,150,GOLD,1.5,15,5,75%
35,36,Jost Chemical,150,GOLD,1.5,15,5,75%
36,37,Colorcon,150,GOLD,1.5,15,5,75%
37,38,Nutra Blend,120,SILVER,1.2,14,6,70%
38,39,Prinova USA,120,SILVER,1.2,14,6,70%
39,40,Magtein / ThreoTech LLC,90,BRONZE,0.9,13,7,65%

Trust-adjusted compliance weights for 'vitamin-d3-cholecalciferol' suppliers:
  Prinova USA     | score= 120 | tier=SILVER    | compliance=1.600 × trust=1.200 → adjusted=1.920
  PureBulk        | score= 180 | tier=PLATINUM  | compliance=1.500 × trust=1.500 → adjusted=2.250

In [ ]:
# ─────────────────────────────────────────────────────────────
# CELL 8-OR — Bayesian Beta-Binomial Supplier Trust Score
# ─────────────────────────────────────────────────────────────
# Replaces the additive ±10/20 Go-Fish heuristic with a
# statistically principled Bayesian model.
#
# Model: supplier on-time probability p ~ Beta(α, β)
#
#   Prior       : Beta(α₀=2, β₀=1)  — weak optimistic prior
#   After n deliveries with k on-time:
#   Posterior   : Beta(α₀+k, β₀+(n−k))
#   Trust p̂    : α / (α + β)        — posterior mean
#   Multiplier  : 0.5 + p̂           — maps [0,1] → [0.5, 1.5]
#   95% CI      : credible interval for uncertainty quantification
#
# Key advantage over heuristic:
#   • A supplier with 1/1 delivery ≠ a supplier with 100/100 delivery
#     (the prior regularises small-sample cases)
#   • No arbitrary ±10/20 magic numbers
#   • Uncertainty interval shrinks as evidence accumulates
# ─────────────────────────────────────────────────────────────

from scipy import stats as scipy_stats


class BayesianTrustTracker:
    """Beta-Binomial Bayesian model for supplier reliability."""
    ALPHA_0 = 2.0   # prior pseudo on-time successes
    BETA_0  = 1.0   # prior pseudo delay failures

    def __init__(self):
        self._posterior = {}   # supplier → (alpha, beta)
        self._raw       = {}   # supplier → (n_total, n_on_time)

    def update(self, supplier_name: str, n_total: int, n_on_time: int) -> None:
        alpha = self.ALPHA_0 + n_on_time
        beta  = self.BETA_0  + (n_total - n_on_time)
        self._posterior[supplier_name] = (alpha, beta)
        self._raw[supplier_name]       = (n_total, n_on_time)

    def simulate_and_update(self, supplier_name: str, n_deliveries: int = 20) -> None:
        rng     = random.Random(hash(supplier_name) % (2 ** 31))
        n_on    = sum(1 for _ in range(n_deliveries) if rng.random() < 0.80)
        self.update(supplier_name, n_deliveries, n_on)

    def _get_posterior(self, supplier_name: str):
        if supplier_name not in self._posterior:
            self.simulate_and_update(supplier_name)
        return self._posterior[supplier_name]

    def get_trust_probability(self, supplier_name: str) -> float:
        alpha, beta = self._get_posterior(supplier_name)
        return round(alpha / (alpha + beta), 4)

    def get_trust_multiplier(self, supplier_name: str) -> float:
        return round(0.5 + self.get_trust_probability(supplier_name), 4)

    def get_credible_interval(self, supplier_name: str, ci: float = 0.95):
        alpha, beta = self._get_posterior(supplier_name)
        dist = scipy_stats.beta(alpha, beta)
        lo   = dist.ppf((1 - ci) / 2)
        hi   = dist.ppf(1 - (1 - ci) / 2)
        return round(lo, 4), round(hi, 4)

    def get_trust_tier(self, supplier_name: str) -> str:
        p = self.get_trust_probability(supplier_name)
        if p >= 0.90: return "PLATINUM"
        if p >= 0.80: return "GOLD"
        if p >= 0.70: return "SILVER"
        if p >= 0.55: return "BRONZE"
        return "PROBATION"

    def get_raw(self, supplier_name: str):
        if supplier_name not in self._raw:
            self.simulate_and_update(supplier_name)
        return self._raw[supplier_name]


# ── Initialise for all 40 suppliers ──────────────────────────────────────────
bayes_tracker = BayesianTrustTracker()
for name in all_suppliers["Name"]:
    bayes_tracker.simulate_and_update(name, n_deliveries=20)

# ── Build leaderboard ─────────────────────────────────────────────────────────
bayes_rows = []
for name in all_suppliers["Name"]:
    n_tot, n_on    = bayes_tracker.get_raw(name)
    alpha, beta_   = bayes_tracker._get_posterior(name)
    p_hat          = bayes_tracker.get_trust_probability(name)
    mult           = bayes_tracker.get_trust_multiplier(name)
    tier           = bayes_tracker.get_trust_tier(name)
    ci_lo, ci_hi   = bayes_tracker.get_credible_interval(name)
    bayes_rows.append({
        "supplier_name":       name,
        "deliveries":          n_tot,
        "on_time":             n_on,
        "p_hat":               p_hat,
        "ci_95_low":           ci_lo,
        "ci_95_high":          ci_hi,
        "ci_width":            round(ci_hi - ci_lo, 4),
        "bayesian_mult":       mult,
        "bayes_tier":          tier,
        "alpha_posterior":     round(alpha, 1),
        "beta_posterior":      round(beta_, 1),
    })

df_bayes = (
    pd.DataFrame(bayes_rows)
    .sort_values("p_hat", ascending=False)
    .reset_index(drop=True)
)
df_bayes.insert(0, "rank", df_bayes.index + 1)

SEP = "=" * 70
print(SEP)
print("  CELL 8-OR: BAYESIAN BETA-BINOMIAL TRUST SCORE")
print(SEP)
print(f"  Prior   : Beta(α₀={BayesianTrustTracker.ALPHA_0}, β₀={BayesianTrustTracker.BETA_0})")
print(f"  Update  : posterior = Beta(α₀ + k_on_time,  β₀ + k_delays)")
print(f"  Trust   : p̂ = α/(α+β)  →  multiplier = 0.5 + p̂  ∈ [0.5, 1.5]")
print(SEP)
display(df_bayes[[
    "rank", "supplier_name", "deliveries", "on_time",
    "p_hat", "ci_95_low", "ci_95_high", "ci_width",
    "bayesian_mult", "bayes_tier"
]])

# ── Side-by-side comparison ────────────────────────────────────────────────────
print(f"\n{'─'*70}")
print(f"  Go-Fish Heuristic vs. Bayesian Beta — '{TARGET_INGREDIENT}' suppliers")
print(f"  {'Supplier':<18} {'History':>12} {'Old score':>10} {'Old mult':>9} {'p̂':>8} {'Bayes mult':>11} {'95% CI'}")
print(f"  {'─'*16:<18} {'─'*10:>12} {'─'*8:>10} {'─'*7:>9} {'─'*6:>8} {'─'*9:>11} {'─'*18}")
for s in ["Prinova USA", "PureBulk"]:
    n_tot, n_on = bayes_tracker.get_raw(s)
    old_s  = trust_tracker.get_score(s)
    old_m  = trust_tracker.get_trust_multiplier(s)
    p_hat  = bayes_tracker.get_trust_probability(s)
    b_mult = bayes_tracker.get_trust_multiplier(s)
    ci_lo, ci_hi = bayes_tracker.get_credible_interval(s)
    print(f"  {s:<18} {n_on}/{n_tot} on-time {old_s:>8}  {old_m:>9.3f} {p_hat:>8.4f} {b_mult:>11.4f}  [{ci_lo:.3f}, {ci_hi:.3f}]")

print(f"\n  The 95% CI reveals HOW CERTAIN we are about each supplier's reliability.")
print(f"  After only 20 deliveries, the interval is wide — the Bayesian model")
print(f"  correctly flags this uncertainty; the heuristic gives false precision.")

In [10]:
# ─────────────────────────────────────────────────────────────
# CELL 9 — Supply Chain Risk Heat Map (Vulnerability Index)
# ─────────────────────────────────────────────────────────────
# Scans all 143 fragmented ingredients and scores each by:
#
#   vulnerability_index = total_bom_appearances / distinct_supplier_count
#
# Higher index = more dangerous: high demand concentrated in few suppliers.
# Single-source ingredients are flagged CRITICAL regardless of volume.
# ─────────────────────────────────────────────────────────────

# ── Supplier count per ingredient (from coverage data already loaded) ─────────
df_supplier_counts = (
    df_supplier_coverage
    .groupby("ingredient_name")["supplier_name"]
    .nunique()
    .reset_index()
    .rename(columns={"supplier_name": "supplier_count"})
)

# ── BOM totals per ingredient ─────────────────────────────────────────────────
df_bom_totals = (
    df_fragmented
    .groupby("ingredient_name")
    .agg(
        total_bom_appearances = ("bom_appearances", "sum"),
        company_count         = ("company_name",    "nunique"),
    )
    .reset_index()
)

# ── Merge and score ───────────────────────────────────────────────────────────
df_risk = df_bom_totals.merge(df_supplier_counts, on="ingredient_name")
df_risk["vulnerability_index"] = (
    df_risk["total_bom_appearances"] / df_risk["supplier_count"]
).round(2)


def _risk_tier(row: pd.Series) -> str:
    if row["supplier_count"] == 1:
        return "CRITICAL"
    if row["supplier_count"] == 2 and row["total_bom_appearances"] >= 20:
        return "HIGH"
    if row["total_bom_appearances"] >= 15:
        return "MEDIUM"
    return "LOW"


df_risk["risk_tier"] = df_risk.apply(_risk_tier, axis=1)
df_risk = df_risk.sort_values("vulnerability_index", ascending=False).reset_index(drop=True)
df_risk.insert(0, "rank", df_risk.index + 1)

# ── Summary ───────────────────────────────────────────────────────────────────
SEP = "=" * 70
print(SEP)
print("  AGNES — SUPPLY CHAIN RISK HEAT MAP")
print(SEP)
print(f"  Total ingredients analyzed : {len(df_risk)}")
print(f"  CRITICAL  (1 supplier)     : {(df_risk['risk_tier'] == 'CRITICAL').sum()}")
print(f"  HIGH      (2 sup, ≥20 BOM) : {(df_risk['risk_tier'] == 'HIGH').sum()}")
print(f"  MEDIUM    (≥15 BOMs)       : {(df_risk['risk_tier'] == 'MEDIUM').sum()}")
print(f"  LOW                        : {(df_risk['risk_tier'] == 'LOW').sum()}")
print(SEP)
print("\nTop 15 most vulnerable ingredients:")
display(
    df_risk.head(15)[[
        "rank", "ingredient_name", "total_bom_appearances",
        "company_count", "supplier_count", "vulnerability_index", "risk_tier"
    ]]
)

======================================================================
  AGNES — SUPPLY CHAIN RISK HEAT MAP
======================================================================
  Total ingredients analyzed : 143
  CRITICAL  (1 supplier)     : 18
  HIGH      (2 sup, ≥20 BOM) : 11
  MEDIUM    (≥15 BOMs)       : 9
  LOW                        : 105
======================================================================

Top 15 most vulnerable ingredients:

,rank,ingredient_name,total_bom_appearances,company_count,supplier_count,vulnerability_index,risk_tier
0,1,maltodextrin,21,8,1,21.0,CRITICAL
1,2,glycerin,17,8,1,17.0,CRITICAL
2,3,vitamin-d3-cholecalciferol,33,17,2,16.5,HIGH
3,4,magnesium-stearate,30,11,2,15.0,HIGH
4,5,gelatin,30,11,2,15.0,HIGH
5,6,microcrystalline-cellulose,29,13,2,14.5,HIGH
6,7,citric-acid,26,12,2,13.0,HIGH
7,8,natural-flavor,13,8,1,13.0,CRITICAL
8,9,silicon-dioxide,25,10,2,12.5,HIGH
9,10,magnesium-oxide,25,10,2,12.5,HIGH
10,11,vitamin-c,24,13,2,12.0,HIGH
11,12,stearic-acid,24,7,2,12.0,HIGH
12,13,calcium-carbonate,20,8,2,10.0,HIGH
13,14,whey-protein-isolate,20,11,2,10.0,HIGH
14,15,croscarmellose-sodium,19,8,2,9.5,MEDIUM

In [ ]:
# ─────────────────────────────────────────────────────────────
# CELL 9-OR — TOPSIS Multi-Attribute Risk Heat Map
# ─────────────────────────────────────────────────────────────
# Replaces the single-ratio vulnerability_index (BOM / supplier_count)
# with TOPSIS (Technique for Order of Preference by Similarity to
# Ideal Solution), a classical MCDM method.
#
# Four risk criteria (all cost — higher = riskier):
#   C1: total_bom_appearances   weight=0.35  demand at risk
#   C2: company_count           weight=0.20  breadth of impact
#   C3: 1 / supplier_count      weight=0.30  concentration (inverted)
#   C4: avg_lead_time_days      weight=0.15  sourcing delay risk
#
# Also computes:
#   HHI = Σ(BOM_share_s)²          — supplier concentration index
#   Shannon Entropy = −Σ p·log(p)  — diversification score (inverse of HHI)
# ─────────────────────────────────────────────────────────────

import numpy as np

TOPSIS_WEIGHTS = [0.35, 0.20, 0.30, 0.15]   # must sum to 1.0


def compute_topsis(df_matrix: pd.DataFrame, weights: list) -> pd.Series:
    """
    TOPSIS scoring over a decision matrix.
    All criteria are assumed cost (higher = riskier = closer to positive ideal).
    Returns a score in [0, 1] — higher means higher risk.
    """
    X = df_matrix.values.astype(float)
    w = np.array(weights)

    # Step 1: Vector normalisation
    col_norms = np.sqrt((X ** 2).sum(axis=0))
    col_norms[col_norms == 0] = 1e-10
    R = X / col_norms

    # Step 2: Weighted normalised matrix
    V = R * w

    # Step 3: Positive-ideal (max risk) and negative-ideal (min risk)
    A_pos = V.max(axis=0)
    A_neg = V.min(axis=0)

    # Step 4: Euclidean distances
    d_pos = np.sqrt(((V - A_pos) ** 2).sum(axis=1))
    d_neg = np.sqrt(((V - A_neg) ** 2).sum(axis=1))

    # Step 5: Closeness coefficient (proximity to negative-ideal = how risky)
    denom = d_pos + d_neg
    denom[denom == 0] = 1e-10
    return pd.Series(d_neg / denom, index=df_matrix.index)


def compute_hhi(ingredient_name: str) -> float:
    """HHI = Σ (BOM_share_s)². HHI=1 → monopoly; HHI→0 → diversified."""
    df_ing = df_supplier_coverage[df_supplier_coverage["ingredient_name"] == ingredient_name]
    if df_ing.empty:
        return 1.0
    total = df_ing["bom_appearances"].sum()
    if total == 0:
        return 1.0
    shares = df_ing.groupby("supplier_name")["bom_appearances"].sum() / total
    return round(float((shares ** 2).sum()), 4)


def compute_shannon_entropy(ingredient_name: str) -> float:
    """H = −Σ p_s·log(p_s). H=0 → single source; max(H)=log(n) → diversified."""
    df_ing = df_supplier_coverage[df_supplier_coverage["ingredient_name"] == ingredient_name]
    if df_ing.empty:
        return 0.0
    total = df_ing["bom_appearances"].sum()
    if total == 0:
        return 0.0
    shares = df_ing.groupby("supplier_name")["bom_appearances"].sum() / total
    return round(float(-(shares * np.log(shares + 1e-12)).sum()), 4)


def _avg_lead_time(ingredient_name: str) -> float:
    """Average lead time across all suppliers for an ingredient (mock data)."""
    suppliers = df_supplier_coverage[
        df_supplier_coverage["ingredient_name"] == ingredient_name
    ]["supplier_name"].unique()
    if len(suppliers) == 0:
        return 14.0
    times = [scrape_supplier_compliance(s, ingredient_name)["lead_time_days"] for s in suppliers]
    return float(np.mean(times))


# ── Build criteria matrix ──────────────────────────────────────────────────────
criteria_rows = []
for _, row in df_risk.iterrows():
    ing = row["ingredient_name"]
    criteria_rows.append({
        "ingredient_name":    ing,
        "total_bom":          float(row["total_bom_appearances"]),
        "company_count":      float(row["company_count"]),
        "inv_supplier_count": float(1.0 / max(1, row["supplier_count"])),
        "avg_lead_time":      _avg_lead_time(ing),
    })

df_criteria = pd.DataFrame(criteria_rows).set_index("ingredient_name")

topsis_scores = compute_topsis(
    df_criteria[["total_bom", "company_count", "inv_supplier_count", "avg_lead_time"]],
    TOPSIS_WEIGHTS,
)

# ── Concentration indices ──────────────────────────────────────────────────────
hhi_vals     = {ing: compute_hhi(ing)             for ing in df_criteria.index}
entropy_vals = {ing: compute_shannon_entropy(ing) for ing in df_criteria.index}

# ── Assemble TOPSIS risk table ─────────────────────────────────────────────────
df_risk_or = df_risk[[
    "ingredient_name", "total_bom_appearances", "company_count",
    "supplier_count", "vulnerability_index", "risk_tier"
]].copy()

df_risk_or["topsis_score"] = df_risk_or["ingredient_name"].map(topsis_scores).round(4)
df_risk_or["hhi"]          = df_risk_or["ingredient_name"].map(hhi_vals)
df_risk_or["shannon_h"]    = df_risk_or["ingredient_name"].map(entropy_vals)

# TOPSIS-based risk tier (percentile thresholds)
t_vals = df_risk_or["topsis_score"].values
q90, q75, q55 = np.percentile(t_vals, 90), np.percentile(t_vals, 75), np.percentile(t_vals, 55)

def _topsis_tier(s):
    if s >= q90: return "CRITICAL"
    if s >= q75: return "HIGH"
    if s >= q55: return "MEDIUM"
    return "LOW"

df_risk_or["topsis_tier"] = df_risk_or["topsis_score"].map(_topsis_tier)
df_risk_or = df_risk_or.sort_values("topsis_score", ascending=False).reset_index(drop=True)
df_risk_or.insert(0, "or_rank", df_risk_or.index + 1)

# ── Output ─────────────────────────────────────────────────────────────────────
SEP = "=" * 70
print(SEP)
print("  CELL 9-OR: TOPSIS MULTI-ATTRIBUTE RISK HEAT MAP")
print(SEP)
print(f"  Method    : TOPSIS (4 criteria) + HHI + Shannon Entropy")
print(f"  Criteria  : C1=bom_appearances(w={TOPSIS_WEIGHTS[0]}),  C2=company_count(w={TOPSIS_WEIGHTS[1]})")
print(f"              C3=1/supplier_count(w={TOPSIS_WEIGHTS[2]}), C4=avg_lead_time(w={TOPSIS_WEIGHTS[3]})")
print(SEP)
print(f"\n  TOPSIS risk tier distribution:")
for tier in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
    n = (df_risk_or["topsis_tier"] == tier).sum()
    print(f"    {tier:<8} : {n:>3} ingredients")

print(f"\nTop 15 highest-risk ingredients (TOPSIS ranking):")
display(df_risk_or.head(15)[[
    "or_rank", "ingredient_name", "total_bom_appearances", "company_count",
    "supplier_count", "topsis_score", "hhi", "shannon_h", "topsis_tier",
    "vulnerability_index", "risk_tier"
]])

# ── Rank shift comparison ──────────────────────────────────────────────────────
old_rank_map = {row["ingredient_name"]: i + 1 for i, row in df_risk.iterrows()}
print(f"\n{'─'*70}")
print("  Heuristic rank vs. TOPSIS rank (top 10)")
print(f"  {'TOPSIS':>6}  {'Ingredient':<35} {'Old rank':>8}  {'Shift':>6}")
print(f"  {'─'*6:>6}  {'─'*33:<35} {'─'*7:>8}  {'─'*5:>6}")
for i, row in df_risk_or.head(10).iterrows():
    old_r = old_rank_map.get(row["ingredient_name"], "?")
    shift = (old_r - (i + 1)) if isinstance(old_r, int) else 0
    arrow = f"↑{shift}" if shift > 0 else (f"↓{abs(shift)}" if shift < 0 else "  =")
    print(f"  {i+1:>6}  {row['ingredient_name']:<35} {old_r:>8}  {arrow:>6}")

print(f"\n  Key: TOPSIS elevates ingredients with wide lead-time spread and")
print(f"  high company count — dimensions invisible to the simple BOM/supplier ratio.")

In [11]:
# ─────────────────────────────────────────────────────────────
# CELL 10 — Supply Chain Disruption Simulator
# ─────────────────────────────────────────────────────────────
# "What if Prinova USA goes offline tomorrow?"
# Agnes identifies all affected ingredients, companies, and BOMs,
# finds alternate suppliers, and calls Gemini once for a consolidated
# contingency recommendation — not once per ingredient.
# ─────────────────────────────────────────────────────────────

DISRUPTED_SUPPLIER = "Prinova USA"

# ── Query 1: All ingredients covered by the disrupted supplier ────────────────
SQL_DISRUPTED = """
WITH parsed AS (
    SELECT
        p.Id AS product_id,
        p.CompanyId,
        c.Name AS company_name,
        SUBSTR(
            SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-')),
            1,
            LENGTH(SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-'))) - 9
        ) AS ingredient_name
    FROM Product p
    JOIN Company c ON c.Id = p.CompanyId
    WHERE p.Type = 'raw-material'
),
bom_usage AS (
    SELECT
        pr.ingredient_name,
        pr.company_name,
        pr.product_id,
        COUNT(bc.BOMId) AS bom_appearances
    FROM parsed pr
    JOIN BOM_Component bc ON bc.ConsumedProductId = pr.product_id
    GROUP BY pr.product_id
)
SELECT
    bu.ingredient_name,
    SUM(bu.bom_appearances)      AS bom_appearances_at_risk,
    COUNT(DISTINCT bu.company_name) AS companies_at_risk
FROM bom_usage bu
JOIN Supplier_Product sp ON sp.ProductId = bu.product_id
JOIN Supplier s           ON s.Id        = sp.SupplierId
WHERE s.Name = :supplier
GROUP BY bu.ingredient_name
ORDER BY bom_appearances_at_risk DESC
"""

# ── Query 2: Alternate suppliers per ingredient (excluding disrupted one) ─────
SQL_ALTERNATES = """
WITH parsed AS (
    SELECT
        p.Id AS product_id,
        SUBSTR(
            SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-')),
            1,
            LENGTH(SUBSTR(p.SKU, 4 + INSTR(SUBSTR(p.SKU, 4), '-'))) - 9
        ) AS ingredient_name
    FROM Product p
    WHERE p.Type = 'raw-material'
)
SELECT DISTINCT
    pr.ingredient_name,
    s.Name AS alternate_supplier
FROM parsed pr
JOIN Supplier_Product sp ON sp.ProductId = pr.product_id
JOIN Supplier s           ON s.Id        = sp.SupplierId
WHERE s.Name != :supplier
"""

conn = sqlite3.connect(DB_PATH)
df_disrupted  = pd.read_sql_query(SQL_DISRUPTED,  conn, params={"supplier": DISRUPTED_SUPPLIER})
df_alternates = pd.read_sql_query(SQL_ALTERNATES, conn, params={"supplier": DISRUPTED_SUPPLIER})
conn.close()

# ── Annotate with backup availability ────────────────────────────────────────
alt_map = df_alternates.groupby("ingredient_name")["alternate_supplier"].apply(list).to_dict()

df_disrupted["alternate_suppliers"] = df_disrupted["ingredient_name"].map(
    lambda ing: ", ".join(alt_map.get(ing, [])) or "NONE"
)
df_disrupted["has_backup"] = df_disrupted["ingredient_name"].map(
    lambda ing: len(alt_map.get(ing, [])) > 0
)
df_disrupted["exposure"] = df_disrupted["has_backup"].map(
    {True: "MANAGEABLE", False: "CRITICAL EXPOSURE"}
)

critical_count = int((~df_disrupted["has_backup"]).sum())

SEP = "=" * 70
print(SEP)
print(f"  AGNES — DISRUPTION SIMULATOR: '{DISRUPTED_SUPPLIER}' goes offline")
print(SEP)
print(f"  Ingredients directly affected : {len(df_disrupted)}")
print(f"  Total BOM appearances at risk : {int(df_disrupted['bom_appearances_at_risk'].sum())}")
print(f"  Ingredients with NO backup    : {critical_count}  ← CRITICAL EXPOSURE")
print(SEP)
display(
    df_disrupted[[
        "ingredient_name", "bom_appearances_at_risk",
        "companies_at_risk", "alternate_suppliers", "exposure"
    ]].head(20)
)

# ── Single Gemini call: consolidated contingency plan ────────────────────────
top_critical   = df_disrupted[~df_disrupted["has_backup"]].head(3)
top_manageable = df_disrupted[df_disrupted["has_backup"]].head(3)

critical_list = "\n".join(
    f"  - {r['ingredient_name']} ({r['bom_appearances_at_risk']} BOM appearances, NO backup)"
    for _, r in top_critical.iterrows()
) or "  None"

manageable_list = "\n".join(
    f"  - {r['ingredient_name']} ({r['bom_appearances_at_risk']} BOMs → backup: {r['alternate_suppliers']})"
    for _, r in top_manageable.iterrows()
)

disruption_prompt = f"""## Supply Chain Disruption Alert

{DISRUPTED_SUPPLIER} has gone offline due to a facility shutdown.

### Impact Summary
- {len(df_disrupted)} ingredients affected
- {int(df_disrupted['bom_appearances_at_risk'].sum())} total BOM appearances at risk
- {critical_count} ingredients have NO alternate supplier (critical exposure)

### Critical Exposure — no backup available:
{critical_list}

### Manageable — backup suppliers exist:
{manageable_list}

### Task
Provide an immediate contingency plan for CPG procurement teams.

Respond in JSON:
{{
  "risk_level": "<CRITICAL | HIGH | MEDIUM>",
  "highest_priority_ingredient": "<name>",
  "immediate_actions": ["<action 1>", "<action 2>", "<action 3>"],
  "week_1_actions": ["<action 1>", "<action 2>"],
  "month_1_actions": ["<action 1>", "<action 2>"],
  "strategic_recommendation": "<2-3 sentences on long-term sourcing strategy>"
}}"""

print(f"\nCalling Gemini for contingency plan …")
disruption_resp = client.models.generate_content(
    model="gemini-flash-latest",
    contents=disruption_prompt,
    config=types.GenerateContentConfig(
        response_mime_type="application/json",
        temperature=0.2,
    ),
)
contingency = json.loads(disruption_resp.text.strip())

SEP2 = "─" * 70
print(f"\n{SEP2}")
print("AGNES CONTINGENCY PLAN")
print(SEP2)
print(f"  Risk level         : {contingency.get('risk_level', 'N/A')}")
print(f"  Highest priority   : {contingency.get('highest_priority_ingredient', 'N/A')}")
print(f"\n  IMMEDIATE (24 h):")
for a in contingency.get("immediate_actions", []):
    print(f"    • {a}")
print(f"\n  WEEK 1:")
for a in contingency.get("week_1_actions", []):
    print(f"    • {a}")
print(f"\n  MONTH 1:")
for a in contingency.get("month_1_actions", []):
    print(f"    • {a}")
print(f"\n  Strategic recommendation:")
print(f"  {contingency.get('strategic_recommendation', '')}")

======================================================================
  AGNES — DISRUPTION SIMULATOR: 'Prinova USA' goes offline
======================================================================
  Ingredients directly affected : 135
  Total BOM appearances at risk : 712
  Ingredients with NO backup    : 0  ← CRITICAL EXPOSURE
======================================================================

,ingredient_name,bom_appearances_at_risk,companies_at_risk,alternate_suppliers,exposure
0,vitamin-d3-cholecalciferol,33,17,PureBulk,MANAGEABLE
1,citric-acid,26,12,Univar Solutions,MANAGEABLE
2,magnesium-oxide,25,10,Jost Chemical,MANAGEABLE
3,vitamin-c,24,13,PureBulk,MANAGEABLE
4,whey-protein-isolate,20,11,Actus Nutrition,MANAGEABLE
5,vitamin-e,19,10,PureBulk,MANAGEABLE
6,vitamin-a,19,10,PureBulk,MANAGEABLE
7,riboflavin,18,8,PureBulk,MANAGEABLE
8,biotin,18,6,PureBulk,MANAGEABLE
9,zinc,17,11,Jost Chemical,MANAGEABLE
10,whey-protein-concentrate,17,8,Actus Nutrition,MANAGEABLE
11,acesulfame-potassium,17,8,Cargill,MANAGEABLE
12,vitamin-d3,14,8,PureBulk,MANAGEABLE
13,magnesium,14,11,Jost Chemical,MANAGEABLE
14,vitamin-d,13,7,PureBulk,MANAGEABLE
15,ascorbic-acid,13,7,PureBulk,MANAGEABLE
16,sucralose,11,9,Univar Solutions,MANAGEABLE
17,folic-acid,11,3,PureBulk,MANAGEABLE
18,cyanocobalamin,11,5,PureBulk,MANAGEABLE
19,b-vitamins,11,9,PureBulk,MANAGEABLE

Calling Gemini for contingency plan …

──────────────────────────────────────────────────────────────────────
AGNES CONTINGENCY PLAN
──────────────────────────────────────────────────────────────────────
  Risk level         : HIGH
  Highest priority   : vitamin-d3-cholecalciferol

  IMMEDIATE (24 h):
    • Contact PureBulk, Univar Solutions, and Jost Chemical to secure existing spot-buy inventory.
    • Place immediate bridge orders for the top 10 ingredients by BOM volume to prevent production line stoppages.
    • Issue a formal notice to the production planning team regarding potential lead-time extensions for 712 BOMs.

  WEEK 1:
    • Conduct a comprehensive audit of the remaining 132 ingredients to verify and activate all secondary supplier contracts.
    • Validate the quality specifications of backup suppliers against existing Prinova-sourced COAs to ensure formulation compatibility.

  MONTH 1:
    • Onboard and qualify at least one additional tertiary supplier for high-volume ingredients like Citric Acid and Vitamin D3.
    • Perform a post-mortem on safety stock levels and adjust minimum inventory thresholds for all 135 affected ingredients.

  Strategic recommendation:
  Shift from a single-distributor reliance to a diversified multi-sourcing strategy that distributes volume across at least two geographically distinct suppliers per ingredient. Implement a robust supplier risk monitoring system to provide early warnings on facility-specific shutdowns and logistics bottlenecks.

In [12]:
# ─────────────────────────────────────────────────────────────
# CELL 11 — Buying Consortium Recommender (GPO Opportunities)
# ─────────────────────────────────────────────────────────────
# Identifies clusters of CPG companies buying the same ingredient
# independently from the same limited supplier pool.
# Recommends forming a Group Purchasing Organization (GPO) to
# unlock collective negotiating leverage.
#
# consortium_leverage_score = total_bom_appearances × company_count × 0.10
# (proxy for estimated negotiating leverage gain)
# ─────────────────────────────────────────────────────────────

# ── Build candidate ingredients: 5+ companies, narrow supplier pool ───────────
df_ingredient_summary = (
    df_fragmented
    .groupby("ingredient_name")
    .agg(
        company_count         = ("company_name", "nunique"),
        total_bom_appearances = ("bom_appearances", "sum"),
        companies             = ("company_name", lambda x: sorted(x.unique().tolist())),
    )
    .reset_index()
)

df_ingredient_summary = df_ingredient_summary.merge(df_supplier_counts, on="ingredient_name")

df_consortium = df_ingredient_summary[
    df_ingredient_summary["company_count"] >= 5
].copy()

df_consortium["consortium_leverage_score"] = (
    df_consortium["total_bom_appearances"] * df_consortium["company_count"] * 0.10
).round(1)

df_consortium["est_leverage_gain"] = df_consortium["company_count"].map(
    lambda n: f"+{min(25, round(n * 1.5)):.0f}% negotiating leverage"
)

df_consortium = (
    df_consortium
    .sort_values("consortium_leverage_score", ascending=False)
    .reset_index(drop=True)
)
df_consortium.insert(0, "rank", df_consortium.index + 1)

SEP = "=" * 70
print(SEP)
print("  AGNES — BUYING CONSORTIUM RECOMMENDATIONS (GPO Opportunities)")
print(SEP)
print(f"  Consortium candidates : {len(df_consortium)}")
print(f"  (ingredients bought independently by 5+ CPG companies)")
print(SEP)
print("\nTop 10 Group Purchasing Opportunities:")
display(
    df_consortium.head(10)[[
        "rank", "ingredient_name", "company_count", "total_bom_appearances",
        "supplier_count", "consortium_leverage_score", "est_leverage_gain"
    ]]
)

# ── LLM call: GPO recommendation for the #1 opportunity ─────────────────────
top = df_consortium.iloc[0]
shown_companies = top["companies"][:8]
company_str = ", ".join(shown_companies)
if len(top["companies"]) > 8:
    company_str += f" … (+{len(top['companies']) - 8} more)"

consortium_prompt = f"""## Group Purchasing Organization Opportunity

Agnes has identified a major buying consortium opportunity.

### Ingredient: {top['ingredient_name']}
- Companies buying independently : {top['company_count']} ({company_str})
- Total BOM appearances          : {top['total_bom_appearances']}
- Available suppliers            : {top['supplier_count']} (limited pool)
- Status today                   : Each company negotiates alone → zero combined leverage

### Task
Agnes recommends these companies form a Group Purchasing Organization (GPO).
Provide the business case, structure, and first action step.

Respond in JSON:
{{
  "gpo_recommendation": "<2-3 sentence executive summary>",
  "estimated_savings_pct": "<X-Y% range>",
  "structure_suggestion": "<how to organize the GPO: lead buyer, shared contract, etc.>",
  "key_risks": ["<risk 1>", "<risk 2>", "<risk 3>"],
  "first_step": "<the single most important first action>"
}}"""

print(f"\nCalling Gemini for GPO recommendation on '{top['ingredient_name']}' …")
gpo_resp = client.models.generate_content(
    model="gemini-flash-latest",
    contents=consortium_prompt,
    config=types.GenerateContentConfig(
        response_mime_type="application/json",
        temperature=0.2,
    ),
)
gpo = json.loads(gpo_resp.text.strip())

SEP2 = "─" * 70
print(f"\n{SEP2}")
print(f"GPO RECOMMENDATION: {top['ingredient_name'].upper()}")
print(SEP2)
print(f"  Companies in consortium : {top['company_count']}")
print(f"  Combined BOM demand     : {top['total_bom_appearances']} appearances")
print(f"  Estimated savings       : {gpo.get('estimated_savings_pct', 'N/A')}")
print(f"\n  Recommendation:")
print(f"  {gpo.get('gpo_recommendation', '')}")
print(f"\n  Structure:")
print(f"  {gpo.get('structure_suggestion', '')}")
print(f"\n  Key risks:")
for r in gpo.get("key_risks", []):
    print(f"    • {r}")
print(f"\n  First step: {gpo.get('first_step', '')}")

======================================================================
  AGNES — BUYING CONSORTIUM RECOMMENDATIONS (GPO Opportunities)
======================================================================
  Consortium candidates : 51
  (ingredients bought independently by 5+ CPG companies)
======================================================================

Top 10 Group Purchasing Opportunities:

,rank,ingredient_name,company_count,total_bom_appearances,supplier_count,consortium_leverage_score,est_leverage_gain
0,1,vitamin-d3-cholecalciferol,17,33,2,56.1,+25% negotiating leverage
1,2,microcrystalline-cellulose,13,29,2,37.7,+20% negotiating leverage
2,3,gelatin,11,30,2,33.0,+16% negotiating leverage
3,4,magnesium-stearate,11,30,2,33.0,+16% negotiating leverage
4,5,vitamin-c,13,24,2,31.2,+20% negotiating leverage
5,6,citric-acid,12,26,2,31.2,+18% negotiating leverage
6,7,magnesium-oxide,10,25,2,25.0,+15% negotiating leverage
7,8,silicon-dioxide,10,25,2,25.0,+15% negotiating leverage
8,9,whey-protein-isolate,11,20,2,22.0,+16% negotiating leverage
9,10,vitamin-a,10,19,2,19.0,+15% negotiating leverage

Calling Gemini for GPO recommendation on 'vitamin-d3-cholecalciferol' …

──────────────────────────────────────────────────────────────────────
GPO RECOMMENDATION: VITAMIN-D3-CHOLECALCIFEROL
──────────────────────────────────────────────────────────────────────
  Companies in consortium : 17
  Combined BOM demand     : 33 appearances
  Estimated savings       : 12-22%

  Recommendation:
  Consolidating the purchasing power of 17 major supplement brands for Vitamin D3 will shift the market dynamic from fragmented buyers to a unified block. Given the limited supplier pool of only two providers, a GPO provides the necessary scale to secure volume discounts and ensure supply priority in a constrained market.

  Structure:
  A Third-Party Managed GPO model where a neutral entity negotiates a Master Service Agreement (MSA) with the two suppliers, allowing individual companies to issue purchase orders against the pre-negotiated volume-based price tiers.

  Key risks:
    • Anti-trust and price-fixing regulatory scrutiny
    • Supply chain vulnerability due to extreme concentration on only two suppliers
    • Difficulty in aligning quality specifications and testing protocols across 17 different brands

  First step: Execute a multi-party Non-Disclosure Agreement (NDA) to conduct a confidential spend analysis and aggregate the total annual tonnage requirements across all 17 participants.

In [ ]:
# ─────────────────────────────────────────────────────────────
# CELL 11-OR — Shapley Value Group Purchasing Organization
# ─────────────────────────────────────────────────────────────
# Uses cooperative game theory (Shapley value) to fairly allocate
# GPO savings among the 17 companies buying vitamin-d3-cholecalciferol.
#
# Value function v(S) for coalition S:
#   v(S) = total_volume(S) × base_unit_price × discount_rate(|S|) − overhead
#
# Volume discount tiers (illustrative):
#   1–3  companies : 3%  discount
#   4–7  companies : 7%  discount
#   8–12 companies : 12% discount
#   13+  companies : 18% discount
#
# Shapley formula:
#   φᵢ = Σ_{S ⊆ N∖{i}} [|S|!(|N|−|S|−1)! / |N|!] × [v(S∪{i}) − v(S)]
#
# Complexity: O(n × 2ⁿ) — n=17 companies → ~1.1M evaluations (feasible).
# ─────────────────────────────────────────────────────────────

from itertools import combinations
from math import factorial
from functools import lru_cache

# ── Discount schedule ─────────────────────────────────────────────────────────
_DISCOUNT_TIERS = [(13, 0.18), (8, 0.12), (4, 0.07), (1, 0.03)]

def _discount_rate(n_companies: int) -> float:
    for min_n, rate in _DISCOUNT_TIERS:
        if n_companies >= min_n:
            return rate
    return 0.0

# ── Company volumes (BOM appearances as proxy for order volume) ───────────────
_company_volumes = df_target.set_index("company_name")["bom_appearances"].to_dict()
_companies_list  = sorted(_company_volumes.keys())

BASE_UNIT_PRICE       = 50.0    # $/unit (illustrative)
COORDINATION_OVERHEAD = 200.0   # fixed overhead per coalition

@lru_cache(maxsize=None)
def _v(coalition: frozenset) -> float:
    """Cached coalition value function."""
    if not coalition:
        return 0.0
    total_vol = sum(_company_volumes.get(c, 0) for c in coalition)
    discount  = _discount_rate(len(coalition))
    return max(0.0, total_vol * BASE_UNIT_PRICE * discount - COORDINATION_OVERHEAD)


def compute_shapley_values(players: list) -> dict:
    """Exact Shapley values using definition formula. O(n × 2^n)."""
    n   = len(players)
    den = factorial(n)
    phi = {p: 0.0 for p in players}
    for player in players:
        others = [p for p in players if p != player]
        for size in range(n):
            w = factorial(size) * factorial(n - size - 1) / den
            for coal in combinations(others, size):
                S      = frozenset(coal)
                S_with = S | {player}
                phi[player] += w * (_v(S_with) - _v(S))
    return phi


# ── Run ───────────────────────────────────────────────────────────────────────
print(f"Computing Shapley values for {len(_companies_list)} companies …")
print(f"Evaluating ≤ {len(_companies_list) * 2**(len(_companies_list)-1):,} marginal contributions …\n")

phi = compute_shapley_values(_companies_list)

grand_value = _v(frozenset(_companies_list))
total_phi   = sum(phi.values())

# ── Results DataFrame ─────────────────────────────────────────────────────────
shapley_rows = []
for company in _companies_list:
    bom_vol = _company_volumes.get(company, 0)
    shapley_rows.append({
        "company_name":         company,
        "bom_volume_proxy":     bom_vol,
        "shapley_value":        round(phi[company], 2),
        "shapley_share_pct":    round(phi[company] / total_phi * 100, 1) if total_phi > 0 else 0.0,
        "naive_proratio_pct":   round(bom_vol / sum(_company_volumes.values()) * 100, 1),
    })

df_shapley = (
    pd.DataFrame(shapley_rows)
    .sort_values("shapley_value", ascending=False)
    .reset_index(drop=True)
)
df_shapley.insert(0, "rank", df_shapley.index + 1)

SEP = "=" * 70
print(SEP)
print("  CELL 11-OR: SHAPLEY VALUE — FAIR GPO SAVINGS ALLOCATION")
print(SEP)
print(f"  Ingredient       : {TARGET_INGREDIENT}")
print(f"  Coalition members: {len(_companies_list)} CPG companies")
print(f"  Grand coalition  : ${grand_value:,.2f} total savings")
print(f"  Σ Shapley values : ${total_phi:,.2f}  (efficiency check: {abs(total_phi - grand_value) < 0.01})")
print(SEP)
display(df_shapley)

print(f"\n{'─'*70}")
print("  Shapley vs. Naive Pro-Rata Comparison")
print(f"  {'Company':<22} {'BOM vol':>8} {'Shapley%':>10} {'Pro-rata%':>11} {'Diff':>8}")
print(f"  {'─'*20:<22} {'─'*7:>8} {'─'*8:>10} {'─'*9:>11} {'─'*6:>8}")
for _, row in df_shapley.iterrows():
    diff  = row["shapley_share_pct"] - row["naive_proratio_pct"]
    arrow = f"+{diff:.1f}" if diff > 0.05 else (f"{diff:.1f}" if diff < -0.05 else "≈0")
    print(f"  {row['company_name']:<22} {row['bom_volume_proxy']:>8} "
          f"  {row['shapley_share_pct']:>8.1f}%  {row['naive_proratio_pct']:>9.1f}%  {arrow:>8}")

print(f"\n  Shapley insight: Companies that push the coalition across a discount")
print(f"  tier boundary receive a larger share than their raw volume suggests.")
print(f"  (e.g., the {_discount_rate(8)*100:.0f}% → {_discount_rate(13)*100:.0f}% jump at 13 companies creates outsized Shapley gain)")

In [13]:
# ─────────────────────────────────────────────────────────────
# CELL 12 — Agnes 2.0 Executive Dashboard (All 143 Ingredients)
# ─────────────────────────────────────────────────────────────
# Aggregates every Agnes signal into a single executive summary:
#   • Fragmentation demand  (Cell 2)
#   • Risk tier             (Cell 9)
#   • Best supplier trust   (Cell 8)
#   • Best compliance weight(Cell 4 + 6)
#   • GPO eligibility       (Cell 11)
#   • Estimated savings     (mocked: 8–15 % per consolidated ingredient)
#
# No LLM calls — pure heuristic scoring across all 143 ingredients
# for speed and cost efficiency during the demo.
# ─────────────────────────────────────────────────────────────

def _best_trust_mult(ingredient_name: str) -> float:
    suppliers = df_supplier_coverage[
        df_supplier_coverage["ingredient_name"] == ingredient_name
    ]["supplier_name"].unique()
    if len(suppliers) == 0:
        return 1.0
    return max(trust_tracker.get_trust_multiplier(s) for s in suppliers)


def _best_compliance_weight(ingredient_name: str) -> float:
    suppliers = df_supplier_coverage[
        df_supplier_coverage["ingredient_name"] == ingredient_name
    ]["supplier_name"].unique()
    if len(suppliers) == 0:
        return 1.0
    return max(
        compute_compliance_weight(scrape_supplier_compliance(s, ingredient_name))
        for s in suppliers
    )


consortium_set = set(df_consortium["ingredient_name"].tolist())

dashboard_rows = []
for _, row in df_risk.iterrows():
    ing         = row["ingredient_name"]
    trust_mult  = _best_trust_mult(ing)
    comp_weight = _best_compliance_weight(ing)
    agnes_score = round(row["total_bom_appearances"] * comp_weight * trust_mult, 1)

    # Deterministic savings estimate (higher risk → more to gain from consolidation)
    rng = random.Random(hash(ing) % (2 ** 31))
    if row["risk_tier"] in ("CRITICAL", "HIGH"):
        est_pct = round(rng.uniform(10.0, 15.0), 1)
    else:
        est_pct = round(rng.uniform(6.0, 11.0), 1)

    dashboard_rows.append({
        "ingredient_name":  ing,
        "companies":        int(row["company_count"]),
        "bom_appearances":  int(row["total_bom_appearances"]),
        "suppliers":        int(row["supplier_count"]),
        "risk_tier":        row["risk_tier"],
        "vuln_index":       row["vulnerability_index"],
        "trust_score":      int(trust_mult * 100),
        "compliance_wt":    round(comp_weight, 3),
        "agnes_score":      agnes_score,
        "est_savings":      f"{est_pct}%",
        "gpo_eligible":     "YES" if ing in consortium_set else "—",
    })

df_dashboard = (
    pd.DataFrame(dashboard_rows)
    .sort_values("agnes_score", ascending=False)
    .reset_index(drop=True)
)
df_dashboard.insert(0, "priority", df_dashboard.index + 1)

# ── Summary statistics ────────────────────────────────────────────────────────
total_boms      = df_dashboard["bom_appearances"].sum()
critical_count  = (df_dashboard["risk_tier"] == "CRITICAL").sum()
gpo_count       = (df_dashboard["gpo_eligible"] == "YES").sum()
avg_savings     = df_dashboard["est_savings"].str.rstrip("%").astype(float).mean()
top_ingredient  = df_dashboard.iloc[0]["ingredient_name"]
top_score       = df_dashboard.iloc[0]["agnes_score"]

SEP = "=" * 75
print(SEP)
print("  AGNES 2.0 — EXECUTIVE DASHBOARD: FULL SUPPLY CHAIN INTELLIGENCE")
print(SEP)
print(f"  Fragmented ingredients analyzed : {len(df_dashboard)}")
print(f"  Total BOM appearances at risk   : {total_boms}")
print(f"  CPG companies involved          : {df_fragmented['company_name'].nunique()}")
print(f"  CRITICAL single-source risks    : {critical_count}")
print(f"  GPO-eligible opportunities      : {gpo_count}")
print(f"  Avg estimated savings           : {avg_savings:.1f}%")
print(SEP)
print("\nTop 20 Consolidation Priorities:")
print("(Agnes Score = BOM demand × best compliance weight × best supplier trust)\n")
display(
    df_dashboard.head(20)[[
        "priority", "ingredient_name", "companies", "bom_appearances",
        "suppliers", "risk_tier", "trust_score",
        "agnes_score", "est_savings", "gpo_eligible"
    ]]
)

SEP2 = "─" * 75
print(f"\n{SEP2}")
print("AGNES 2.0 — SYSTEM INTELLIGENCE SUMMARY")
print(SEP2)
print(f"  Agnes has analyzed {len(df_dashboard)} raw ingredient categories")
print(f"  across {df_fragmented['company_name'].nunique()} CPG companies and {len(all_suppliers)} suppliers.")
print(f"\n  KEY FINDINGS:")
print(f"  [RISK]       {critical_count} ingredients have ZERO backup suppliers — immediate exposure")
print(f"  [GPO]        {gpo_count} ingredients qualify for group purchasing — instant leverage")
print(f"  [TRUST]      Go-Fish scores track 40 suppliers across 20 delivery events each")
print(f"  [DISRUPTION] Simulated {DISRUPTED_SUPPLIER} outage: {len(df_disrupted)} ingredients affected")
print(f"  [PRIORITY]   Top consolidation target: '{top_ingredient}' (Agnes score: {top_score})")
print(f"  [SAVINGS]    Estimated avg. {avg_savings:.1f}% cost reduction across all consolidations")
print(f"\n  Agnes is ready to run deep LLM substitutability analysis")
print(f"  on any of the {len(df_dashboard)} ingredients on demand.")
print(SEP)

===========================================================================
  AGNES 2.0 — EXECUTIVE DASHBOARD: FULL SUPPLY CHAIN INTELLIGENCE
===========================================================================
  Fragmented ingredients analyzed : 143
  Total BOM appearances at risk   : 1214
  CPG companies involved          : 60
  CRITICAL single-source risks    : 18
  GPO-eligible opportunities      : 51
  Avg estimated savings           : 9.4%
===========================================================================

Top 20 Consolidation Priorities:
(Agnes Score = BOM demand × best compliance weight × best supplier trust)

,priority,ingredient_name,companies,bom_appearances,suppliers,risk_tier,trust_score,agnes_score,est_savings,gpo_eligible
0,1,vitamin-d3-cholecalciferol,17,33,2,HIGH,150,79.2,13.6%,YES
1,2,gelatin,11,30,2,HIGH,150,67.5,10.7%,YES
2,3,magnesium-stearate,11,30,2,HIGH,150,67.5,12.1%,YES
3,4,microcrystalline-cellulose,13,29,2,HIGH,150,60.9,13.5%,YES
4,5,magnesium-oxide,10,25,2,HIGH,150,58.1,12.4%,YES
5,6,citric-acid,12,26,2,HIGH,150,52.7,11.7%,YES
6,7,silicon-dioxide,10,25,2,HIGH,150,52.5,11.6%,YES
7,8,vitamin-c,13,24,2,HIGH,150,48.6,13.9%,YES
8,9,stearic-acid,7,24,2,HIGH,150,46.8,11.1%,YES
9,10,maltodextrin,8,21,1,CRITICAL,150,45.7,14.1%,YES
10,11,whey-protein-isolate,11,20,2,HIGH,150,45.0,12.4%,YES
11,12,croscarmellose-sodium,8,19,2,MEDIUM,150,44.2,9.2%,YES
12,13,calcium-carbonate,8,20,2,HIGH,150,40.5,14.5%,YES
13,14,vitamin-e,10,19,2,MEDIUM,150,39.9,8.6%,YES
14,15,glycerin,8,17,1,CRITICAL,150,39.5,11.6%,YES
15,16,vitamin-a,10,19,2,MEDIUM,150,38.5,6.2%,YES
16,17,whey-protein-concentrate,8,17,2,MEDIUM,150,38.2,7.2%,YES
17,18,sunflower-lecithin,7,16,2,MEDIUM,150,37.2,10.3%,YES
18,19,biotin,6,18,2,MEDIUM,150,36.5,10.5%,YES
19,20,zinc,11,17,2,MEDIUM,150,34.4,10.5%,YES

───────────────────────────────────────────────────────────────────────────
AGNES 2.0 — SYSTEM INTELLIGENCE SUMMARY
───────────────────────────────────────────────────────────────────────────
  Agnes has analyzed 143 raw ingredient categories
  across 60 CPG companies and 40 suppliers.

  KEY FINDINGS:
  [RISK]       18 ingredients have ZERO backup suppliers — immediate exposure
  [GPO]        51 ingredients qualify for group purchasing — instant leverage
  [TRUST]      Go-Fish scores track 40 suppliers across 20 delivery events each
  [DISRUPTION] Simulated Prinova USA outage: 135 ingredients affected
  [PRIORITY]   Top consolidation target: 'vitamin-d3-cholecalciferol' (Agnes score: 79.2)
  [SAVINGS]    Estimated avg. 9.4% cost reduction across all consolidations

  Agnes is ready to run deep LLM substitutability analysis
  on any of the 143 ingredients on demand.
===========================================================================